/**
 * Community Knowledge Holder Partnership intake surface (research-side only, ADR-009).
 */
export {
  COMMUNITY_CAMPAIGN_BRIEF_SCHEMA_VERSION,
  COMMUNITY_SUBMISSION_SCHEMA_VERSION,
  COMMUNITY_SUBMISSION_ASSESSMENT_SCHEMA_VERSION,
  COMMUNITY_HOLDER_REGISTRY_SCHEMA_VERSION,
  COMMUNITY_PARTNERSHIP_ADAPTER_ID,
  COMMUNITY_PARTNERSHIP_PARSER_VERSION,
  COMMUNITY_PARTNERSHIP_REGISTRY_ENTRY_ID,
  COMMUNITY_HOLDER_TYPES,
  COMMUNITY_SUBMISSION_FIELD_SPECS,
  COMMUNITY_PARTNERSHIP_CARE_POLICY,
  COMMUNITY_HOLDER_REGISTRY_PATH,
  isCommunityHolderType,
  assertCommunityPartnershipCarePolicy,
  buildCommunityCampaignBrief,
  toCommunitySubmissionPayload,
  communitySubmissionToDiscoveryCandidate,
  scoreCommunitySubmission,
  parseCommunityHolderRegistry,
  loadCommunityHolderRegistry,
  type CommunityHolderType,
  type CommunityHolderClassification,
  type CommunityKnowledgeHolder,
  type CommunityCampaignCounty,
  type CommunitySubmissionFieldSpec,
  type CommunityPartnershipCarePolicy,
  type CommunityCampaignBrief,
  type CommunitySubmission,
  type CommunitySubmissionPayload,
  type CommunitySubmissionRouting,
  type CommunitySubmissionAssessment,
  type ScoreCommunitySubmissionOptions,
  type CommunityHolderRegistryCounty,
  type CommunityHolderRegistry,
} from './community-campaign.js';
