/**
 * Web glyph adapter for destination icons. Semantic ids live in
 * `@repo/public-contracts/destinations`; this is the only web module allowed to
 * name a Font Awesome glyph for one of those ids.
 */
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowUpRightFromSquare,
  faBook,
  faBookOpen,
  faBoxArchive,
  faCalendarDay,
  faChartColumn,
  faChevronDown,
  faCircleInfo,
  faCircleQuestion,
  faClipboard,
  faClock,
  faCommentDots,
  faEllipsis,
  faFilter,
  faFlag,
  faFlask,
  faGavel,
  faGrip,
  faHeart,
  faHouse,
  faLandmark,
  faLayerGroup,
  faLink,
  faList,
  faLocationCrosshairs,
  faLocationDot,
  faMagnifyingGlass,
  faMap,
  faPalette,
  faPaperPlane,
  faPenToSquare,
  faPeopleGroup,
  faSchool,
  faScroll,
  faSeedling,
  faShieldHalved,
  faUser,
  faUserShield,
} from '@fortawesome/free-solid-svg-icons';
import type { DestinationIconId } from '@repo/public-contracts/destinations';

const DESTINATION_GLYPHS: Readonly<Record<DestinationIconId, IconDefinition>> = {
  home: faHouse,
  explore: faMap,
  stories: faBookOpen,
  records: faList,
  rooms: faGrip,
  more: faEllipsis,
  search: faMagnifyingGlass,
  filter: faFilter,
  external: faArrowUpRightFromSquare,
  disclosure: faChevronDown,
  collection: faLayerGroup,
  evidence: faShieldHalved,
  source: faLink,
  precision: faLocationCrosshairs,
  correction: faCommentDots,
  time: faClock,
  person: faUser,
  place: faLocationDot,
  school: faSchool,
  institution: faLandmark,
  organization: faPeopleGroup,
  event: faCalendarDay,
  law: faScroll,
  case: faGavel,
  movement: faFlag,
  publication: faBookOpen,
  artifact: faBoxArchive,
  data: faChartColumn,
  books: faBook,
  memorial: faSeedling,
  about: faCircleInfo,
  questions: faCircleQuestion,
  methodology: faFlask,
  errata: faPenToSquare,
  submit: faPaperPlane,
  support: faHeart,
  privacy: faUserShield,
  terms: faClipboard,
  design: faPalette,
};

export function destinationGlyphFor(id: DestinationIconId): IconDefinition {
  return DESTINATION_GLYPHS[id];
}
