
/**
 * Firestore model surface for BlackStory (ADR-011 019).
 */
export { FIRESTORE_ROOT, firestorePaths } from './paths.js';
export type { FirestoreRootCollection } from './paths.js';

export {
  authClaimFlagsSchema,
  entityKindSchema,
  geoPointFieldsSchema,
  geoGeometrySchema,
  zipCodeInputSchema,
  geographicMatchSchema,
  entityLocationSchema,
  entityAliasSchema,
  entityIdentifierSchema,
  entityMergeStateSchema,
  schoolFieldsSchema,
  policyActiveSchema,
  policyVersionSchema,
  canonicalEntitySchema,
  entityRelationshipSchema,
  entityMergeSchema,
  claimTemporalContextSchema,
  claimGeographicContextSchema,
  confidenceComponentsSchema,
  confidenceScoreSchema,
  preservedClaimValueSchema,
  claimVersionSchema,
  researchCoverageSchema,
  relevanceMeasurementSchema,
  connectionStrengthSchema,
  canonicalClaimSchema,
  claimEvidenceLinkSchema,
  volatilityClassSchema,
  reviewIntervalSchema,
  verificationPolicySchema,
  verificationStatusSchema,
  verificationSubjectTypeSchema,
  verificationStateSchema,
  candidateUpdateStatusSchema,
  candidateUpdateSchema,
  contentHashSchema,
  rightsStatusSchema,
  publicationPermissionSchema,
  prohibitedUseSchema,
  rightsPolicySchema,
  sourceOrganizationSchema,
  sourceDomainSchema,
  evidenceSourceSchema,
  sourceItemSchema,
  retrievalEventSchema,
  sourceCaptureSchema,
  evidenceLocatorSchema,
  evidenceRecordSchema,
  evidenceLineageSchema,
  publicationReleaseSchema,
  publicActiveReleaseSchema,
  publicEntityProjectionSchema,
  publicSearchIndexSchema,
  submissionInboxSchema,
  auditActorSchema,
  auditSubjectSchema,
  auditEventSchema,
  outboxMessageSchema,
  idempotencyRecordSchema,
  outboxConsumerReceiptSchema,
  killSwitchSchema,
  discoveryCampaignRunSchema,
} from './types.js';
export type {
  AuthClaimFlags,
  EntityKindDoc,
  GeoPointFields,
  GeoGeometryDoc,
  ZipCodeInputDoc,
  GeographicMatchDoc,
  EntityLocationDoc,
  PolicyActiveDoc,
  PolicyVersionDoc,
  CanonicalEntityDoc,
  EntityRelationshipDoc,
  EntityMergeDoc,
  ConfidenceComponentsDoc,
  ConfidenceScoreDoc,
  PreservedClaimValueDoc,
  ClaimVersionDoc,
  CanonicalClaimDoc,
  ClaimEvidenceLinkDoc,
  VolatilityClassDoc,
  ReviewIntervalDoc,
  VerificationPolicyDoc,
  VerificationStatusDoc,
  VerificationSubjectTypeDoc,
  VerificationStateDoc,
  CandidateUpdateStatusDoc,
  CandidateUpdateDoc,
  ContentHashDoc,
  RightsPolicyDoc,
  SourceOrganizationDoc,
  SourceDomainDoc,
  EvidenceSourceDoc,
  SourceItemDoc,
  RetrievalEventDoc,
  SourceCaptureDoc,
  EvidenceLocatorDoc,
  EvidenceRecordDoc,
  EvidenceLineageDoc,
  PublicationReleaseDoc,
  PublicActiveReleaseDoc,
  PublicEntityProjectionDoc,
  PublicSearchIndexDoc,
  SubmissionInboxDoc,
  AuditEventDoc,
  OutboxMessageDoc,
  IdempotencyRecordDoc,
  OutboxConsumerReceiptDoc,
  KillSwitchDoc,
  DiscoveryCampaignRunDoc,
} from './types.js';

export {
  parseWithSchema,
  policyActiveConverter,
  policyVersionConverter,
  canonicalEntityConverter,
  entityLocationConverter,
  entityRelationshipConverter,
  entityMergeConverter,
  canonicalClaimConverter,
  claimVersionConverter,
  claimEvidenceLinkConverter,
  sourceOrganizationConverter,
  sourceDomainConverter,
  evidenceSourceConverter,
  sourceItemConverter,
  sourceCaptureConverter,
  retrievalEventConverter,
  evidenceRecordConverter,
  evidenceLineageConverter,
  publicationReleaseConverter,
  publicActiveReleaseConverter,
  publicEntityProjectionConverter,
  preparePublicEntityProjectionForWrite,
  submissionInboxConverter,
  auditEventConverter,
  outboxMessageConverter,
  idempotencyRecordConverter,
  outboxConsumerReceiptConverter,
  killSwitchConverter,
  discoveryCampaignRunConverter,
} from './converters.js';

export {
  DEFAULT_PUBLIC_MEDIA_BUCKET,
  entityPrimaryImageObjectPath,
  entityPrimaryImageObjectRef,
  type EntityPrimaryImageObjectRef,
} from './entity-media.js';

export {
  RELEASE_CATALOG_ARTIFACT_SCHEMA_VERSION,
  buildReleaseCatalogArtifacts,
  publicMediaObjectUrl,
  publicReleaseEntitiesListPath,
  publicReleaseSearchIndexPath,
  writeReleaseCatalogArtifactsToDir,
  uploadReleaseCatalogArtifacts,
  type BuiltReleaseCatalogArtifacts,
  type ReleaseEntitiesListArtifact,
  type ReleaseSearchIndexArtifact,
} from './release-artifacts.js';

export {
  createAdminAtomicStore,
  commitWithAudit,
  consumeOutboxMessage,
  loadEntityPublicationHistory,
} from './audit-outbox.js';
export type {
  AtomicSnapshot,
  AtomicTransaction,
  AtomicStore,
  StateMutation,
  CommitWithAuditInput,
  CommitWithAuditResult,
  ConsumeOutboxResult,
} from './audit-outbox.js';

export { resolveStaffRoles, canPublish, canResearchWrite, researchMayPublish } from './claims.js';
export type { StaffRole } from './claims.js';

export {
  RELEASE_ACTIVATION_STATUSES,
  parseImmutablePublicationRelease,
  resolveActivePublicRelease,
  activatePublicationRelease,
} from './release-activation.js';
export type {
  ReleaseActivationStatus,
  ImmutablePublicationReleaseDoc,
  ActivePublicReleasePointer,
  ActivateReleaseInput,
  ActivateReleaseResult,
} from './release-activation.js';

export { promoteClaimToPublicationCandidate } from './promotion.js';
export type {
  AcceptedPromotionDoc,
  PublicationCandidateDoc,
  PromoteClaimInput,
  PromoteClaimResult,
} from './promotion.js';

export {
  RESEARCH_CASE_SERVER_ACTIONS,
  assertResearchCaseActionAuthorized,
  assertResearchCaseTransitionAuthorized,
  executeAuthorizedResearchCaseTransition,
  executeAuthorizedResearchCaseAction,
} from './research-case.js';
export type {
  ResearchCaseServerAction,
  ServerResearchCaseState,
} from './research-case.js';
