/**
 * Mobile store release gate inventory.
 *
 * One entry per item the release program names as a release gate. Machine gates are answered from
 * the collected evidence bundle (see `checks.ts`); human gates are answered by an attestation and
 * fail closed when none is recorded, the same rule the beta launch gate uses.
 *
 * Two gates are EXPECTED TO FAIL on the current tree and are here deliberately rather than
 * omitted: `ota-code-signing` ( — EAS Update ships unsigned) and, until an owner records
 * it, `store-and-signing-identity`. A gate that is missing because it
 * would be red reads, later, like one nobody thought of.
 */
import type { MobileReleaseGateDefinition } from './types.js';

export const MOBILE_RELEASE_GATES: readonly MobileReleaseGateDefinition[] = [
  {
    id: 'build-provenance',
    title: 'Native artifacts were generated from a known, clean commit with no local overrides',
    kind: 'machine',
    required: true,
    description:
      'The evidence bundle records a full commit SHA with no tracked modifications and no dotenv file in play, so the artifacts the gate judged can be regenerated by someone else.',
    evidence: [
      {
        type: 'command',
        ref: 'git rev-parse HEAD && git status --porcelain',
        description: 'Captured by the collector at the moment it read the native tree.',
      },
    ],
  },
  {
    id: 'ios-bundle-identity',
    title: 'iOS bundle id, display name and version match the declared identity',
    kind: 'machine',
    required: true,
    description:
      'Read from the generated project.pbxproj Release configuration and Info.plist, not from app.config.ts.',
    evidence: [
      {
        type: 'artifact',
        ref: 'apps/mobile/ios/<project>.xcodeproj/project.pbxproj',
        description: 'PRODUCT_BUNDLE_IDENTIFIER in the Release build configuration.',
      },
      { type: 'artifact', ref: 'apps/mobile/ios/<project>/Info.plist' },
    ],
  },
  {
    id: 'ios-os-floor-and-devices',
    title: 'iOS deployment target and device family match the declared floor',
    kind: 'machine',
    required: true,
    description:
      'IPHONEOS_DEPLOYMENT_TARGET equals the declared floor and TARGETED_DEVICE_FAMILY includes iPad, which the adaptive layout work depends on.',
    evidence: [{ type: 'artifact', ref: 'apps/mobile/ios/<project>.xcodeproj/project.pbxproj' }],
  },
  {
    id: 'ios-store-compliance',
    title: 'iOS store declarations are present and consistent with behaviour',
    kind: 'machine',
    required: true,
    description:
      'Export-compliance declaration, App Transport Security, privacy manifest, non-empty permission strings, and the build phase that strips Metro/Bonjour development keys out of a Release binary.',
    evidence: [
      { type: 'artifact', ref: 'apps/mobile/ios/<project>/Info.plist' },
      { type: 'artifact', ref: 'apps/mobile/ios/<project>/PrivacyInfo.xcprivacy' },
    ],
  },
  {
    id: 'ios-associated-domains',
    title: 'Universal links are entitled for the production domain',
    kind: 'machine',
    required: true,
    description:
      'The generated entitlements carry the applinks: entry for the production host. Production only; other variants are skipped.',
    evidence: [{ type: 'artifact', ref: 'apps/mobile/ios/<project>/<project>.entitlements' }],
  },
  {
    id: 'ota-runtime-version',
    title: 'OTA runtime version fences the binary it was built for',
    kind: 'machine',
    required: true,
    description:
      'EXUpdatesRuntimeVersion in the generated Expo.plist equals the app version, under the appVersion policy, so a native-affecting change cannot ship as a JS-only update to an older binary.',
    evidence: [{ type: 'artifact', ref: 'apps/mobile/ios/<project>/Supporting/Expo.plist' }],
  },
  {
    id: 'ota-channel-environment',
    title: 'Update channel, project and API environment agree across config and artifact',
    kind: 'machine',
    required: true,
    description:
      'The EAS project id in the generated update URL matches eas.json, the production profile is a store distribution on the production channel, its API base URL is the expected https origin, and the development profile ships with the native updater disabled.',
    evidence: [
      { type: 'artifact', ref: 'apps/mobile/ios/<project>/Supporting/Expo.plist' },
      { type: 'file', ref: 'apps/mobile/eas.json' },
    ],
  },
  {
    /**
     * NOT REQUIRED, and that is a recorded decision rather than an oversight.
     * `docs/mobile/release/store-account-checklist.md` line 135 accepts the risk explicitly:
     * EAS Update code signing is a paid-plan feature, and the project's posture is free-tier
     * first until budget allows. A required gate that can never go green for a reason the owner
     * already settled trains people to ignore the gate.
     *
     * It stays in the inventory, and it stays red: every decision artifact reports it as an
     * optional failure naming, so the accepted risk is restated on every release
     * rather than forgotten. The required half of this concern is `store-and-signing-identity`,
     * which a person has to sign. Make this required again the day the plan is paid for.
     */
    id: 'ota-code-signing',
    title: 'OTA updates are code signed (accepted risk on the free tier)',
    kind: 'machine',
    required: false,
    description:
      'eas.json declares an update code-signing certificate and the generated plist carries it. Without this an update bundle is trusted on TLS to the update host alone. Tracked as repo-3en3s; risk accepted in the store account checklist while the project is on the free tier.',
    evidence: [
      { type: 'file', ref: 'apps/mobile/eas.json' },
      { type: 'artifact', ref: 'apps/mobile/ios/<project>/Supporting/Expo.plist' },
    ],
  },
  {
    id: 'android-target-sdk',
    title: 'Android target API is proven from Gradle and from the built artifact',
    kind: 'machine',
    required: true,
    description:
      'compileSdk and targetSdk come from a real Gradle invocation, and where a release artifact was built, aapt2 badging on that artifact agrees. Never inferred from the Expo SDK version.',
    evidence: [
      { type: 'command', ref: './gradlew :app:properties' },
      {
        type: 'command',
        ref: 'aapt2 dump badging app/build/outputs/apk/release/app-release.apk',
      },
    ],
  },
  {
    /**
     * REPORT-ONLY (owner decision, 2026-09-14): Wave 9 wants a mobile performance baseline for
     * the first release, with no pass/fail threshold — the program has no prior number to hold
     * this release to, and the "before" half of before/after is unrecoverable for changes
     * already landed. This gate checks that a baseline was collected and is complete, never that
     * any number is fast enough; it can never regress a release on latency or memory.
     */
    id: 'mobile-performance-baseline',
    title: 'A performance baseline was collected and every named metric is accounted for',
    kind: 'machine',
    required: false,
    description:
      'For each platform bundle in the evidence, at least one metric carries a real sample, and every metric the release program names is either measured or listed as unmeasured with a reason. No threshold is applied to any value.',
    evidence: [
      {
        type: 'command',
        ref: 'node scripts/release/mobile-perf-baseline.mjs --platform ios|android --runs 5',
        description:
          'Collected per platform on a booted Simulator / running Emulator, never a physical device.',
      },
      { type: 'doc', ref: 'docs/mobile/release/release-gates.md' },
    ],
  },
  {
    id: 'e2e-release-build',
    title: 'End-to-end journeys pass on the release build',
    kind: 'human',
    required: true,
    description:
      'Operator attests the critical journeys were exercised on the release binary this evidence bundle describes, not on a development client against Metro.',
    evidence: [{ type: 'doc', ref: 'apps/mobile/README.md' }],
  },
  {
    id: 'accessibility-evidence',
    title: 'Accessibility evidence recorded for this release',
    kind: 'human',
    required: true,
    description:
      'Operator attests the screen-reader, focus-order and text-scaling passes were run against this build and their findings filed.',
    evidence: [{ type: 'doc', ref: 'docs/testing/a11y-seo-perf-privacy.md' }],
  },
  {
    id: 'rollback-rehearsed',
    title: 'Rollback path rehearsed for this release',
    kind: 'human',
    required: true,
    description:
      'Operator attests the update-rollback path was exercised, not merely documented, and names what was rolled back and how long it took.',
    evidence: [{ type: 'doc', ref: 'apps/mobile/src/updates/README.md' }],
  },
  {
    id: 'store-and-signing-identity',
    title: 'Store records and signing identity exist and match the build',
    kind: 'human',
    required: true,
    description:
      'Operator attests the App Store Connect and Play Console records exist for this bundle id, a release signing identity exists, and the store disclosures match what the binary actually does. Tracked as repo-arlr and repo-1etxc.',
    evidence: [{ type: 'doc', ref: 'docs/mobile/release/store-account-checklist.md' }],
  },
] as const;

export type MobileReleaseGateId = (typeof MOBILE_RELEASE_GATES)[number]['id'];

export const REQUIRED_HUMAN_RELEASE_GATE_IDS = MOBILE_RELEASE_GATES.filter(
  (gate) => gate.kind === 'human' && gate.required,
).map((gate) => gate.id);
