/**
 * Typed catalog of rights-cleared archive collage tiles used by atmosphere planes.
 * Paths are local copies under /brand/collage/tiles — sourced from Commons promotions
 * (see packages/firebase/scripts/build-archive-collage-tiles.ts).
 *
 * Regenerated by the collage build script — do not hand-edit the tile list.
 */
export type AtmosphereTileCredit = {
  readonly index: string;
  readonly entityId: string;
  /** Local static path served by the web app. */
  readonly path: string;
  /** Original GCS URL recorded in the collage manifest (attribution / rebuild). */
  readonly sourceUrl: string;
};

/** 47-tile pool — index order matches public/brand/collage/tiles/manifest.json. */
export const ATMOSPHERE_TILE_CREDITS: readonly AtmosphereTileCredit[] = [
  {
    index: '01',
    entityId: 'ent_maggie_l_walker_001',
    path: '/brand/collage/tiles/01.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_maggie_l_walker_001/primary.jpg',
  },
  {
    index: '02',
    entityId: 'ent_ursula_burns_001',
    path: '/brand/collage/tiles/02.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_ursula_burns_001/primary.jpg',
  },
  {
    index: '03',
    entityId: 'ent_kenneth_chenault_001',
    path: '/brand/collage/tiles/03.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_kenneth_chenault_001/primary.jpg',
  },
  {
    index: '04',
    entityId: 'ent_robert_l_johnson_001',
    path: '/brand/collage/tiles/04.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_robert_l_johnson_001/primary.jpg',
  },
  {
    index: '05',
    entityId: 'ent_john_h_johnson_001',
    path: '/brand/collage/tiles/05.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_john_h_johnson_001/primary.jpg',
  },
  {
    index: '06',
    entityId: 'ent_bessie_coleman_001',
    path: '/brand/collage/tiles/06.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_bessie_coleman_001/primary.jpg',
  },
  {
    index: '07',
    entityId: 'ent_eugene_bullard_001',
    path: '/brand/collage/tiles/07.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_eugene_bullard_001/primary.jpg',
  },
  {
    index: '08',
    entityId: 'ent_willa_brown_001',
    path: '/brand/collage/tiles/08.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_willa_brown_001/primary.jpg',
  },
  {
    index: '09',
    entityId: 'ent_guion_bluford_001',
    path: '/brand/collage/tiles/09.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_guion_bluford_001/primary.jpg',
  },
  {
    index: '10',
    entityId: 'ent_mae_jemison_001',
    path: '/brand/collage/tiles/10.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_mae_jemison_001/primary.jpg',
  },
  {
    index: '11',
    entityId: 'ent_ronald_mcnair_001',
    path: '/brand/collage/tiles/11.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_ronald_mcnair_001/primary.jpg',
  },
  {
    index: '12',
    entityId: 'ent_charles_bolden_001',
    path: '/brand/collage/tiles/12.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_charles_bolden_001/primary.jpg',
  },
  {
    index: '13',
    entityId: 'ent_robert_h_lawrence_001',
    path: '/brand/collage/tiles/13.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_robert_h_lawrence_001/primary.jpg',
  },
  {
    index: '14',
    entityId: 'ent_katherine_johnson_001',
    path: '/brand/collage/tiles/14.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_katherine_johnson_001/primary.jpg',
  },
  {
    index: '15',
    entityId: 'ent_dorothy_vaughan_001',
    path: '/brand/collage/tiles/15.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_dorothy_vaughan_001/primary.jpg',
  },
  {
    index: '16',
    entityId: 'ent_patricia_bath_001',
    path: '/brand/collage/tiles/16.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_patricia_bath_001/primary.jpg',
  },
  {
    index: '17',
    entityId: 'ent_ernest_everett_just_001',
    path: '/brand/collage/tiles/17.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_ernest_everett_just_001/primary.jpg',
  },
  {
    index: '18',
    entityId: 'ent_marie_maynard_daly_001',
    path: '/brand/collage/tiles/18.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_marie_maynard_daly_001/primary.jpg',
  },
  {
    index: '19',
    entityId: 'ent_james_mccune_smith_001',
    path: '/brand/collage/tiles/19.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_james_mccune_smith_001/primary.jpg',
  },
  {
    index: '20',
    entityId: 'ent_alexa_canady_001',
    path: '/brand/collage/tiles/20.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_alexa_canady_001/primary.jpg',
  },
  {
    index: '21',
    entityId: 'ent_garrett_morgan_001',
    path: '/brand/collage/tiles/21.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_garrett_morgan_001/primary.jpg',
  },
  {
    index: '22',
    entityId: 'ent_frederick_mckinley_jones_001',
    path: '/brand/collage/tiles/22.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_frederick_mckinley_jones_001/primary.jpg',
  },
  {
    index: '23',
    entityId: 'ent_granville_woods_001',
    path: '/brand/collage/tiles/23.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_granville_woods_001/primary.jpg',
  },
  {
    index: '24',
    entityId: 'ent_elijah_mccoy_001',
    path: '/brand/collage/tiles/24.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_elijah_mccoy_001/primary.jpg',
  },
  {
    index: '25',
    entityId: 'ent_george_washington_carver_001',
    path: '/brand/collage/tiles/25.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_george_washington_carver_001/primary.jpg',
  },
  {
    index: '26',
    entityId: 'ent_otis_boykin_001',
    path: '/brand/collage/tiles/26.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_otis_boykin_001/primary.jpg',
  },
  {
    index: '27',
    entityId: 'ent_norbert_rillieux_001',
    path: '/brand/collage/tiles/27.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_norbert_rillieux_001/primary.jpg',
  },
  {
    index: '28',
    entityId: 'ent_sarah_e_goode_001',
    path: '/brand/collage/tiles/28.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_sarah_e_goode_001/primary.jpg',
  },
  {
    index: '29',
    entityId: 'ent_emmett_chappelle_001',
    path: '/brand/collage/tiles/29.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_emmett_chappelle_001/primary.jpg',
  },
  {
    index: '30',
    entityId: 'ent_solomon_carter_fuller_001',
    path: '/brand/collage/tiles/30.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_solomon_carter_fuller_001/primary.jpg',
  },
  {
    index: '31',
    entityId: 'ent_african_meeting_house_001',
    path: '/brand/collage/tiles/31.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_african_meeting_house_001/primary.jpg',
  },
  {
    index: '32',
    entityId: 'ent_ebenezer_baptist_atlanta_001',
    path: '/brand/collage/tiles/32.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_ebenezer_baptist_atlanta_001/primary.jpg',
  },
  {
    index: '33',
    entityId: 'ent_clayborn_temple_001',
    path: '/brand/collage/tiles/33.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_clayborn_temple_001/primary.jpg',
  },
  {
    index: '34',
    entityId: 'ent_chicago_freedom_movement_001',
    path: '/brand/collage/tiles/34.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_chicago_freedom_movement_001/primary.jpg',
  },
  {
    index: '35',
    entityId: 'ent_orangeburg_massacre_001',
    path: '/brand/collage/tiles/35.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_orangeburg_massacre_001/primary.jpg',
  },
  {
    index: '36',
    entityId: 'ent_gaston_motel_001',
    path: '/brand/collage/tiles/36.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_gaston_motel_001/primary.jpg',
  },
  {
    index: '37',
    entityId: 'ent_martin_luther_king_jr_001',
    path: '/brand/collage/tiles/37.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_martin_luther_king_jr_001/primary.jpg',
  },
  {
    index: '38',
    entityId: 'ent_malcolm_x_001',
    path: '/brand/collage/tiles/38.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_malcolm_x_001/primary.jpg',
  },
  {
    index: '39',
    entityId: 'ent_ella_baker_001',
    path: '/brand/collage/tiles/39.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_ella_baker_001/primary.jpg',
  },
  {
    index: '40',
    entityId: 'ent_bayard_rustin_001',
    path: '/brand/collage/tiles/40.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_bayard_rustin_001/primary.jpg',
  },
  {
    index: '41',
    entityId: 'ent_fannie_lou_hamer_001',
    path: '/brand/collage/tiles/41.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_fannie_lou_hamer_001/primary.jpg',
  },
  {
    index: '42',
    entityId: 'ent_john_lewis_001',
    path: '/brand/collage/tiles/42.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_john_lewis_001/primary.jpg',
  },
  {
    index: '43',
    entityId: 'ent_james_meredith_001',
    path: '/brand/collage/tiles/43.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_james_meredith_001/primary.jpg',
  },
  {
    index: '44',
    entityId: 'ent_ralph_abernathy_001',
    path: '/brand/collage/tiles/44.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_ralph_abernathy_001/primary.jpg',
  },
  {
    index: '45',
    entityId: 'ent_hosea_williams_001',
    path: '/brand/collage/tiles/45.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_hosea_williams_001/primary.jpg',
  },
  {
    index: '46',
    entityId: 'ent_charles_sherrod_001',
    path: '/brand/collage/tiles/46.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_charles_sherrod_001/primary.jpg',
  },
  {
    index: '47',
    entityId: 'ent_james_bevel_001',
    path: '/brand/collage/tiles/47.jpg',
    sourceUrl:
      'https://storage.googleapis.com/black-book-efaaf-public-media/public/entities/ent_james_bevel_001/primary.jpg',
  },
] as const;

export const ATMOSPHERE_ATTRIBUTION_HREF = '/stories/mosaic-credits';
