/**
 * `/faq` copy.
 *
 * The questions are the ones a stranger actually asks in the first two minutes, in their own
 * words, including the two that are uncomfortable to answer: who is behind this, and how much of
 * it is machine-made. A marketing question ("What makes BlackStory different?") is not a question
 * anybody has ever typed, and none is here.
 *
 * VOICE. Same split as `/about`. An answer that states how the system behaves is impersonal; an
 * answer that is a person's choice, limit or invitation is first person, because one person runs
 * this and the honest answer to "will this last" is his to give. Nothing here says "we".
 *
 * EVERY ANSWER IS CHECKABLE. Nothing is described here that the repository does not already do:
 *   - grades and their definitions: `packages/domain/src/facts/confidence.ts` and
 *     `app/methodology/methodology-copy.ts` (`EVIDENCE_GRADE_DEFINITIONS`)
 *   - precision and dignity rules: `methodology-copy.ts` (`DIGNITY_RULES`)
 *   - coverage honesty: `methodology-copy.ts` (`LIMITATION_RULES`) and `components/story/story-copy.ts`
 *   - corrections, receipt code, one appeal: `app/corrections/CorrectionsSections.tsx`
 *   - leads reviewed before publication: the `/submit` registry entry and `about-copy.ts`
 *   - the writing pipeline: `docs/content/neo-voice.md` Part VIII,
 *     `docs/methodology/chapter-fact-validation.md`, the `blackstory-prose-review` and
 *     `blackstory-ringer-review` skills, and the gates in `packages/ops-data/scripts/articles.ts`
 *   - cover plates: `brand/cover-lock/v1/README.md` and
 *     `packages/domain/src/publication/cover-package.ts`
 *   - the citation command: `components/patterns/command-palette/command-registry.ts`
 * If an answer here ever outruns those files, the answer is wrong, not the files.
 *
 * NO MODEL NAMES, NO VERSIONS. Naming a vendor dates the page and tells a reader nothing they can
 * check. What matters is which decisions a machine is allowed to make, and that does not change
 * when the tooling does.
 */

import { SUPPORT_CONTACT } from '../../lib/config/contact';

export type FaqLink = {
  readonly href: string;
  readonly label: string;
};

export type FaqEntry = {
  /** The question as a reader would type it. */
  readonly question: string;
  /** Consecutive paragraphs. Two is common, one is fine, four is a sign the answer is dodging. */
  readonly answer: readonly string[];
  /** Where to go next. Rendered as a quiet row under the answer, never as a call to action. */
  readonly links?: readonly FaqLink[];
};

export type FaqSection = {
  /** Anchor id, also used by the contents list at the top. */
  readonly id: string;
  readonly heading: string;
  readonly entries: readonly FaqEntry[];
};

export const FAQ_LEDE =
  'Plain answers to what people actually ask, including the two most people are too polite to ask: who is behind this, and how much of it is made by a machine.';

export const FAQ_SECTIONS: readonly FaqSection[] = [
  {
    id: 'who-runs-this',
    heading: 'Who runs this',
    entries: [
      {
        question: 'Who makes this?',
        answer: [
          'One person: Gerald Dagher. There is no staff, no department and no institution behind the name. The maker credit at the bottom of the about page points at the same person who answers the mail.',
        ],
        links: [{ href: '/about', label: 'Why this exists' }],
      },
      {
        question: 'Is this a museum, a university project or a nonprofit?',
        answer: [
          'No. It is a personal project that publishes public records with their sources attached.',
          'Nothing here carries an institution behind it, so the only thing holding a claim up is the citation next to it. That is why the citations sit on the record itself instead of in a bibliography somewhere at the end.',
        ],
      },
    ],
  },
  {
    id: 'ai',
    heading: 'AI, and what it is not allowed to touch',
    entries: [
      {
        question: 'Is the history on this site generated by AI?',
        answer: [
          'No. The facts come from sources: archives, agency databases, court reporters, library catalogs, National Register nominations and published scholarship. Every accepted claim carries the citations it rests on, and you can read them before you decide to believe any of it.',
          'A model never supplies a fact out of its own memory. Facts are gathered from fetched sources and checked before any of the writing starts, and figures that carry weight need two independent sources. Where a detail cannot be traced to a source, it is left out and the sentence is written without it.',
        ],
        links: [{ href: '/methodology', label: 'How a record gets in' }],
      },
      {
        question: 'So where is AI actually used?',
        answer: [
          'In two places. In the research work, to search, read and pull source material that a person then checks against the original. And in drafting the long-form writing, the chapters and articles, under a written voice standard kept in the project as docs/content/neo-voice.md.',
          'What it does not decide: whether a record is true, which sources a claim rests on, what confidence grade it carries, or whether any of it goes live.',
        ],
      },
      {
        question: 'What happens to a chapter after the draft?',
        answer: [
          'Three passes and a gate. First a line-by-line read against the voice standard, for register, for claim grammar, and for the dignity of the people in the file. Then an adversarial review that reads the draft the way a hostile critic would: the sentence a specialist would write a public letter about, the superlative that fails a literal fact check, the twelve seconds that travel badly with the paragraph stripped off. A finding from that review is a hard blocker, and the writer does not get to overrule it.',
          'Then the code gates, which check source tiers, citation integrity and length. A person activates the release at the end. None of those passes can lower the evidence bar: voice never relaxes an evidence gate.',
        ],
      },
      {
        question: 'Are the drawings on the articles AI images?',
        answer: [
          'No. An article cover is a scan of a drawing on paper: dry felt-tip on cream stock, one weight of line, hatch fills, a sliver of burnt ochre.',
          'The publishing check refuses a plate whose file, link or caption points at a stock library or an image generator, so a generated cover cannot go out by accident.',
        ],
      },
    ],
  },
  {
    id: 'records',
    heading: 'How a record gets in',
    entries: [
      {
        question: 'How does something end up on the map?',
        answer: [
          'A candidate turns up, its sources are gathered, a person verifies it against them, and a publish gate decides whether it reaches a public page. Contradictions between sources are written into the record rather than smoothed away.',
        ],
        links: [{ href: '/methodology', label: 'The full method' }],
      },
      {
        question: 'What does the confidence grade mean?',
        answer: [
          'How sure the archive is, in four steps. Established: several independent, high-authority sources agree and there is no serious dispute. Corroborated: two or more independent sources support it, and any gaps left do not undo the core claim. Single source: one source that meets the citation bar, not necessarily wrong and not yet checked against another. Contested: credible sources disagree, or the claim rests on a source with a known reliability problem, and the record names the disagreement.',
          'The grade is always spelled out in words beside its mark, so reading it never depends on telling two colors apart. Crime statistics never enter it. A grade measures independence and closeness to the event, nothing else.',
        ],
        links: [{ href: '/methodology#evidence-grades', label: 'Grades, with the marks' }],
      },
      {
        question: 'Why is there almost nothing near me?',
        answer: [
          'Because coverage follows the paper that survived, and it did not survive evenly. Church minutes, school registers, deeds and National Register nominations are thick in some counties and gone in others, and what has been published so far is thinner still.',
          'A blank patch means the archive has not published there yet. It is not evidence that nothing happened, and it should never be read as one. If you know what belongs there, that is the most useful thing anybody can send.',
        ],
        links: [{ href: '/submit', label: 'Send a lead' }],
      },
      {
        question: 'Why is the pin in the middle of a county instead of on the building?',
        answer: [
          'Either that is all the source supports, or drawing it sharper would put a living person at an address on a public map.',
          'Public precision runs from country down to a city, a campus or an institution, and stops there. A point is drawn no sharper than that, a coarsened point is never labeled as an exact address, and the record states what its coordinate does not claim.',
        ],
      },
    ],
  },
  {
    id: 'when-it-is-wrong',
    heading: 'When it is wrong',
    entries: [
      {
        question: 'I found a mistake. What do I do?',
        answer: [
          'Use the corrections form. You get a receipt code, and it is the only credential for looking up what happened to your report, so keep it somewhere.',
          'A person reads the report against the published sources. If it is accepted, the record changes and the change is published in the errata with the earlier wording still readable. If it is closed and you think that was wrong, one appeal is available against the same code.',
        ],
        links: [
          { href: '/corrections', label: 'Request a correction' },
          { href: '/errata', label: 'What has already been fixed' },
        ],
      },
      {
        question: 'How long does that take?',
        answer: [
          'There is no promised turnaround, and quoting one here would be inventing it. One person reads these. The receipt code is how you check where yours stands instead of waiting on a reply that may sit for a while.',
        ],
      },
      {
        question: 'Can I add something that is missing?',
        answer: [
          'Yes, and please do. Use the lead form. You do not need an account, an affiliation or a credential, and plain language is fine.',
          `I read every lead before anything is published. Nothing you send goes public on arrival, and nothing is published without a source someone else can check. If a form is the wrong shape for what you have, write to me at ${SUPPORT_CONTACT}.`,
        ],
        links: [
          { href: '/submit', label: 'Submit a lead' },
          { href: `mailto:${SUPPORT_CONTACT}`, label: SUPPORT_CONTACT },
        ],
      },
    ],
  },
  {
    id: 'reading-it',
    heading: 'Reading it, and keeping it',
    entries: [
      {
        question: 'Do I need an account?',
        answer: [
          'No. Every public page works without signing in, and nothing here asks you to say who you are in order to read it.',
        ],
      },
      {
        question: 'Can I cite this in a paper or a class?',
        answer: [
          'Yes. Open a record on the map and the Copy citation command, the C key, puts one on your clipboard: the record name, its place and era, its evidence grade, how many sources it rests on, the date you read it, and the link. The same format is shown on the methodology page.',
          'Cite the underlying sources as well. They are listed on the record, and they are the thing actually holding it up.',
        ],
        links: [{ href: '/explore', label: 'Open the map' }],
      },
      {
        question: 'Will this still be here in five years?',
        answer: [
          'I do not know, and I would rather say so than promise you otherwise. I will do my part for as long as I can.',
          'That is part of why every claim names the sources under it, and why the lead and correction lanes are open to anybody: if I stop, the records this points at are still where they have always been, and what is here can be picked up by someone else.',
        ],
      },
    ],
  },
];

/** Every entry, flattened. The em dash guard and the section index both read this. */
export const FAQ_ENTRIES: readonly FaqEntry[] = FAQ_SECTIONS.flatMap((section) => section.entries);
