/**
 * `/faq` wiring and copy contracts.
 *
 * The assertions are about what this page cannot lose. Two of them are the reason the page
 * exists: the AI answer has to be on the page and has to say no (the history is not generated),
 * and the honest-limit answer has to stay honest. A future edit that softens either one is the
 * failure this file is here to catch.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import { FAQ_ENTRIES, FAQ_LEDE, FAQ_SECTIONS } from './faq-copy';
import { destinationFor } from '../../lib/nav/destination-registry';
import { surfaceClassFor } from '../../lib/nav/surface-classes';

const here = dirname(fileURLToPath(import.meta.url));
const pageSource = readFileSync(join(here, 'page.tsx'), 'utf8');

test('/faq is a registered reading room, not an unclassified route', () => {
  // A classified route with no registry entry fails `destination-registry.test.ts`; an entry with
  // no class fails `surface-classes.test.ts`. Asserting both here names the pair at the page.
  assert.equal(surfaceClassFor('/faq'), 'reading');
  const destination = destinationFor('/faq');
  assert.ok(destination, '/faq has no registry entry, so it is in no reader-facing list');
  assert.equal(destination.parent, '/rooms');
  assert.equal(destination.group, 'check');
});

test('the page renders every section and answer from the copy module', () => {
  assert.match(pageSource, /FAQ_SECTIONS/);
  assert.match(pageSource, /FAQ_LEDE/);
  assert.ok(FAQ_LEDE.length > 0);
  assert.ok(FAQ_SECTIONS.length >= 4, 'a FAQ with three sections is a summary');
  assert.ok(FAQ_ENTRIES.length >= 10, 'a FAQ with a handful of questions is a teaser');
  for (const entry of FAQ_ENTRIES) {
    assert.ok(entry.question.endsWith('?'), `not a question: ${entry.question}`);
    assert.ok(entry.answer.length > 0, `unanswered: ${entry.question}`);
  }
});

test('section ids are unique, because the contents list links to them', () => {
  const ids = FAQ_SECTIONS.map((section) => section.id);
  assert.equal(new Set(ids).size, ids.length, 'two sections share an anchor');
});

test('the answers are open on the page, never behind a disclosure', () => {
  // The two answers a reader most needs (who runs this, how AI is used) are exactly the two a
  // collapsed drawer would hide. If this page ever becomes an accordion, that is the cost.
  assert.doesNotMatch(pageSource, /Disclosure/);
  assert.doesNotMatch(pageSource, /<details/);
});

test('the AI question is answered, and the answer is no', () => {
  const generated = FAQ_ENTRIES.find((entry) => /generated by AI/i.test(entry.question));
  assert.ok(generated, 'the question every reader has is not on the page');
  assert.match(generated.answer[0] ?? '', /^No\./, 'the answer leads with the answer');
  const all = FAQ_ENTRIES.flatMap((entry) => entry.answer).join(' ');
  assert.match(all, /from fetched sources/, 'the answer says where facts do come from');
  assert.match(all, /never supplies a fact/, 'and what a model is never allowed to do');
  assert.match(all, /neo-voice\.md/, 'the voice standard is named, so the claim is checkable');
  assert.match(all, /scan of a drawing/, 'the covers are drawn, and the page says so');
});

test('no model vendor or version is named, because that answer would go stale', () => {
  const all = [FAQ_LEDE, ...FAQ_ENTRIES.flatMap((entry) => [entry.question, ...entry.answer])].join(
    ' ',
  );
  assert.doesNotMatch(all, /\b(gpt|claude|gemini|llama|openai|anthropic|midjourney|dall-?e)\b/i);
});

test('the durability answer keeps its limit and does not promise permanence', () => {
  const entry = FAQ_ENTRIES.find((item) => /still be here/i.test(item.question));
  assert.ok(entry, 'the "will this last" question is the one a reader deserves an answer to');
  assert.match(entry.answer.join(' '), /for as long as I can/);
});

test('no answer speaks as an institutional "we"', () => {
  for (const entry of FAQ_ENTRIES) {
    for (const paragraph of [entry.question, ...entry.answer]) {
      assert.doesNotMatch(paragraph, /\b(we|our|ours)\b/i, `institutional plural in: ${paragraph}`);
    }
  }
});

test('user-facing copy avoids em dashes', () => {
  const strings = [
    FAQ_LEDE,
    ...FAQ_SECTIONS.map((section) => section.heading),
    ...FAQ_ENTRIES.flatMap((entry) => [entry.question, ...entry.answer]),
    ...FAQ_ENTRIES.flatMap((entry) => (entry.links ?? []).map((link) => link.label)),
  ];
  for (const value of strings) {
    assert.doesNotMatch(value, /—/);
  }
});
