import type { ExpoConfig } from 'expo/config';

/**
 * App identity per docs/mobile/decisions/mobile-identity.md (MOB-001) and
 * docs/adr/ADR-020-mobile-stack.md (MOB-002).
 *
 * Three environment tiers, matching the three EAS build profiles in eas.json
 * (development / preview / production). The variant is selected by the
 * `APP_VARIANT` env var, which EAS Build sets per-profile (see eas.json's
 * `env` blocks) and which defaults to `development` for a bare local
 * `expo start` / `expo prebuild` with no env var set, so a fresh clone never
 * accidentally targets production.
 *
 * Per ADR-020 SS6, `ios/` and `android/` are NOT committed — they are
 * regenerated by `expo prebuild` (Continuous Native Generation) from this
 * file plus config plugins. This file is the single source of truth for
 * native identity, never a checked-in native project.
 */

type AppVariant = 'development' | 'preview' | 'production';

const APP_VARIANT = (process.env.APP_VARIANT as AppVariant | undefined) ?? 'development';

// Bundle / application identifiers per mobile-identity.md's proposed scheme.
// These are *proposed* identifiers (dev/preview safe to reference; the bare
// production id `app.blackbook.mobile` is referenced only, never submitted
// to a store — mobile-identity.md human gate #4 must clear availability
// first).
const BUNDLE_IDS: Record<AppVariant, string> = {
  development: 'app.blackbook.mobile.dev',
  preview: 'app.blackbook.mobile.preview',
  production: 'app.blackbook.mobile',
};

// Display name carries an environment suffix for dev/preview so a device
// with multiple variants installed side-by-side (a real Expo/EAS pattern,
// each variant has a distinct bundle id above so they *can* coexist) is
// visibly distinguishable on the home screen. Production uses the bare
// product name.
const APP_NAMES: Record<AppVariant, string> = {
  development: 'BlackStory (Dev)',
  preview: 'BlackStory (Preview)',
  production: 'BlackStory',
};

const bundleIdentifier = BUNDLE_IDS[APP_VARIANT];
const appName = APP_NAMES[APP_VARIANT];

const config: ExpoConfig = {
  name: appName,
  // EAS project slug placeholder — no Expo/EAS organization has been
  // provisioned yet (mobile-identity.md human gate #3). This slug becomes
  // meaningful only once a real EAS project is linked (`eas init`); it
  // creates no store or EAS resource by itself.
  slug: 'blackstory-mobile',
  version: '1.0.0',
  orientation: 'portrait',
  // Custom URL scheme fallback per mobile-identity.md: `blackstory://`,
  // deliberately distinct from the reverse-DNS bundle id for readability in
  // support docs/marketing. Universal links / associated domains
  // (`blackbook.app`) are deferred to MOB-008/MOB-020 per that doc.
  scheme: 'blackstory',
  userInterfaceStyle: 'automatic',
  // No `newArchEnabled` toggle: SDK 56 has fully removed the legacy
  // architecture, so New Architecture is the only supported mode and the
  // config field no longer exists (confirmed against
  // @expo/config-types@ExpoConfig for this SDK).
  icon: './assets/images/icon.png',
  ios: {
    // Native minimum OS floor per ADR-020 SS7, re-verified at this scaffold
    // (MOB-006) as that section requires: SDK 56's actual iOS platform
    // minimum is 16.4 (raised from SDK 54's ~15.1, per `pod install`
    // evidence — several Expo-bundled pods, including `expo` itself,
    // require iOS 16.4), which is *above* ADR-020's proposed 16.0 floor. Per
    // ADR-020 SS7 ("whichever SDK MOB-006 actually pins governs"), the
    // platform floor now governs: 16.4, not the originally proposed 16.0.
    deploymentTarget: '16.4',
    bundleIdentifier,
    icon: './assets/expo.icon',
    // TODO(MOB-010): once real Firebase iOS apps exist for each bundle id
    // (a human gate — see mobile-identity.md gates #1/#3), wire
    // GoogleService-Info.plist via a config plugin (e.g.
    // `@react-native-firebase/app`'s plugin) keyed by APP_VARIANT. No
    // Firebase config file is committed by this bead; do not fabricate one.
    //
    // Universal Links (MOB-008, mobile-identity.md's URL-scheme section, threat-model T4
    // "Universal-link domain binding"): declares this app as the handler for
    // https://blackbook.app/* links, verified by iOS against the real
    // apple-app-site-association file served from that domain's /.well-known/ path. Only
    // production points at the bare production domain; dev/preview builds never claim it
    // (avoids a dev build racing production for the same verified domain on a shared test
    // device). The AASA file itself is a local template only — see
    // apps/mobile/public/.well-known/README.md for what's real vs. templated, and
    // mobile-identity.md's open human gates (#1: Apple Team ID) for what's still missing
    // before this can be verified/published for real.
    associatedDomains: APP_VARIANT === 'production' ? ['applinks:blackbook.app'] : [],
  },
  android: {
    // Native minimum OS floor per ADR-020 SS7: Android 8.0 (API 26)+.
    package: bundleIdentifier,
    adaptiveIcon: {
      backgroundColor: '#E6F4FE',
      foregroundImage: './assets/images/android-icon-foreground.png',
      backgroundImage: './assets/images/android-icon-background.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
    // TODO(MOB-010): wire google-services.json via a config plugin per
    // APP_VARIANT once real Firebase Android apps exist. Not committed here.
    //
    // Android App Links (MOB-008), the Android analogue of iOS associatedDomains above:
    // autoVerify asks Android to verify this app against the real assetlinks.json served
    // from https://blackbook.app/.well-known/assetlinks.json before treating the app as the
    // default handler for that host — see apps/mobile/public/.well-known/README.md for
    // what's templated vs. real (this needs a real Android signing SHA-256, mobile-identity.md
    // human gate #2, which doesn't exist yet). Production-only, same rationale as iOS.
    intentFilters:
      APP_VARIANT === 'production'
        ? [
            {
              action: 'VIEW',
              autoVerify: true,
              data: [{ scheme: 'https', host: 'blackbook.app' }],
              category: ['BROWSABLE', 'DEFAULT'],
            },
          ]
        : [],
  },
  web: {
    output: 'static',
    favicon: './assets/images/favicon.png',
  },
  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        backgroundColor: '#208AEF',
        image: './assets/images/splash-icon.png',
        imageWidth: 76,
      },
    ],
    [
      // Enforces the Android API-level floor (ADR-020 SS7); iOS's floor is
      // set directly via `ios.deploymentTarget` above (a native ExpoConfig
      // field with no plugin needed).
      'expo-build-properties',
      {
        android: {
          minSdkVersion: 26,
        },
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
  extra: {
    appVariant: APP_VARIANT,
    // No `eas.projectId` yet — no EAS organization/project is provisioned
    // (mobile-identity.md human gate #3). Added by `eas init` once that
    // gate clears; do not hand-write a fake project id here.
  },
};

export default config;
