import { existsSync } from 'node:fs';

import type { ExpoConfig } from 'expo/config';

/**
 * App identity per docs/mobile/decisions/mobile-identity.md (MOB-001) and
 * docs/adr/ADR-020-mobile-stack.md (MOB-002).
 *
 * Three environment tiers, matching the three EAS build profiles in eas.json
 * (development / preview / production). The variant is selected by the
 * `APP_VARIANT` env var, which EAS Build sets per-profile (see eas.json's
 * `env` blocks) and which defaults to `development` for a bare local
 * `expo start` / `expo prebuild` with no env var set, so a fresh clone never
 * accidentally targets production.
 *
 * Per ADR-020 SS6, `ios/` and `android/` are NOT committed — they are
 * regenerated by `expo prebuild` (Continuous Native Generation) from this
 * file plus config plugins. This file is the single source of truth for
 * native identity, never a checked-in native project.
 */

type AppVariant = 'development' | 'preview' | 'production';

const APP_VARIANT = (process.env.APP_VARIANT as AppVariant | undefined) ?? 'development';

// --- Config validation helpers ----------------------------------------------
//
// app.config.ts is evaluated by `expo start` / `expo prebuild` / EAS Build, so
// throwing here fails a MISCONFIGURED build fast and loudly rather than
// shipping a silently-wrong binary. These helpers validate the small set of
// env inputs this config reads. They NEVER print an env *value* that could be
// sensitive — only its name, and for URLs/enums the offending token/protocol —
// so a malformed input can't leak a credential into a build log. No production
// credential is ever fabricated: unset optional inputs fall back to safe,
// non-secret defaults, and the Firebase native config is a real file on disk
// (or an EAS file secret), never invented here.

function failConfig(message: string): never {
  throw new Error(`[app.config] ${message}`);
}

/**
 * Validate an optional absolute http(s) URL env var, falling back when unset.
 * Production MUST be https (never ship cleartext attestation/API traffic);
 * dev/preview may use http for a LAN/localhost host.
 */
function resolveHttpUrl(
  name: string,
  raw: string | undefined,
  fallback: string,
): string {
  const value = (raw ?? '').trim() || fallback;
  let parsed: URL;
  try {
    parsed = new URL(value);
  } catch {
    return failConfig(`${name} is not a valid absolute URL`);
  }
  if (parsed.protocol !== 'https:' && parsed.protocol !== 'http:') {
    return failConfig(`${name} must be an http(s) URL (got "${parsed.protocol}//…")`);
  }
  if (APP_VARIANT === 'production' && parsed.protocol !== 'https:') {
    return failConfig(
      `${name} must use https:// for the production variant (got "${parsed.protocol}//…") — refusing to ship cleartext traffic`,
    );
  }
  return value;
}

/** Parse the perf-trace sample rate, bounded to `[0, 1]`; unset → 10%. */
function resolveSampleRate(raw: string | undefined): number {
  if (raw === undefined || raw.trim() === '') {
    return 0.1;
  }
  const value = Number(raw);
  if (!Number.isFinite(value) || value < 0 || value > 1) {
    return failConfig(`PERFORMANCE_SAMPLE_RATE must be a number in [0, 1] (got "${raw}")`);
  }
  return value;
}

/**
 * Resolve the (client-advisory) App Check enforcement stage. Unset → `monitor`.
 * A typo is a hard error so a build can never silently mean something other
 * than the two valid stages; `enforce` must be opted into deliberately.
 */
function resolveEnforcementModeEnv(raw: string | undefined): 'monitor' | 'enforce' {
  const value = (raw ?? '').trim();
  if (value === '' || value === 'monitor') {
    return 'monitor';
  }
  if (value === 'enforce') {
    return 'enforce';
  }
  return failConfig(`APP_CHECK_ENFORCEMENT_MODE must be "monitor" or "enforce" (got "${value}")`);
}

/**
 * Resolve the Firebase native config file paths from env. The files themselves
 * are NEVER committed (see .gitignore); their paths come from a gitignored
 * local file or an EAS file secret at build time. Both platforms must be
 * supplied together (a half-configured Firebase app is a misconfiguration),
 * and a supplied path must actually exist so `expo prebuild` fails here with a
 * clear message instead of deep inside a native plugin.
 */
function resolveFirebaseConfigFiles(): {
  readonly plist: string | undefined;
  readonly json: string | undefined;
  readonly present: boolean;
} {
  const plist = process.env.GOOGLE_SERVICES_INFO_PLIST?.trim() || undefined;
  const json = process.env.GOOGLE_SERVICES_JSON?.trim() || undefined;
  if (Boolean(plist) !== Boolean(json)) {
    failConfig(
      'GOOGLE_SERVICES_INFO_PLIST (iOS) and GOOGLE_SERVICES_JSON (Android) must be set together or not at all — exactly one was provided',
    );
  }
  for (const [name, file] of [
    ['GOOGLE_SERVICES_INFO_PLIST', plist],
    ['GOOGLE_SERVICES_JSON', json],
  ] as const) {
    if (file && !existsSync(file)) {
      failConfig(`${name} points to a file that does not exist: ${file}`);
    }
  }
  return { plist, json, present: Boolean(plist && json) };
}

// Bundle / application identifiers per mobile-identity.md's proposed scheme.
// These are *proposed* identifiers (dev/preview safe to reference; the bare
// production id `app.blackbook.mobile` is referenced only, never submitted
// to a store — mobile-identity.md human gate #4 must clear availability
// first).
const BUNDLE_IDS: Record<AppVariant, string> = {
  development: 'app.blackbook.mobile.dev',
  preview: 'app.blackbook.mobile.preview',
  production: 'app.blackbook.mobile',
};

// Display name carries an environment suffix for dev/preview so a device
// with multiple variants installed side-by-side (a real Expo/EAS pattern,
// each variant has a distinct bundle id above so they *can* coexist) is
// visibly distinguishable on the home screen. Production uses the bare
// product name.
const APP_NAMES: Record<AppVariant, string> = {
  development: 'BlackStory (Dev)',
  preview: 'BlackStory (Preview)',
  production: 'BlackStory',
};

const bundleIdentifier = BUNDLE_IDS[APP_VARIANT];
const appName = APP_NAMES[APP_VARIANT];

// --- App Check / Firebase native config (MOB-010) ----------------------------
//
// No real Firebase iOS/Android app is registered yet and NO
// GoogleService-Info.plist / google-services.json is committed (a human
// gate — see mobile-identity.md gates #1/#3 and README "Firebase config —
// intentionally not committed"). The `@react-native-firebase/app` config
// plugin THROWS at `expo prebuild` if it is enabled without a real config
// file present, so the plugins are wired into a SLOT that activates only once
// the file paths are supplied via env (set per-EAS-profile once the gate
// clears). Until then, `expo prebuild` runs cleanly with App Check absent and
// the client degrades gracefully (see src/security/app-check.ts). Do NOT
// fabricate a placeholder credential file to "turn this on".
const firebaseConfigFiles = resolveFirebaseConfigFiles();
const GOOGLE_SERVICES_INFO_PLIST = firebaseConfigFiles.plist;
const GOOGLE_SERVICES_JSON = firebaseConfigFiles.json;
const firebaseConfigPresent = firebaseConfigFiles.present;

// Public, non-secret Firebase project identifier (see
// infra/firebase/registered-apps.json — apiKey/appId/projectId are Firebase
// *identifiers* restricted by App Check + domain, not server secrets). Only the
// project id is surfaced to JS via `extra.firebase` for diagnostics; the actual
// native credential is the GoogleService file copied by the config plugin, not
// this string. Overridable per-build via env; defaults to the registered
// production project.
const FIREBASE_PROJECT_ID = process.env.FIREBASE_PROJECT_ID?.trim() || 'black-book-efaaf';

// --- API surface config (MOB-004 wire contract; MOB-016 corrections) --------
//
// The native reader talks to `apps/api-public` (and, once distinct, a
// submissions host) over HTTPS. These are NON-SECRET public origins, safe to
// bake into a build and read at runtime from `extra` (see
// src/security/bootstrap.ts + src/features/corrections/runtime.ts). Set per
// EAS profile via the non-secret `env` blocks in eas.json; a production build
// is rejected above if handed a cleartext (http) origin.
const DEFAULT_API_BASE_URL = 'https://api.blackbook.app';
const API_BASE_URL = resolveHttpUrl('API_BASE_URL', process.env.API_BASE_URL, DEFAULT_API_BASE_URL);
const SUBMISSIONS_BASE_URL = resolveHttpUrl(
  'SUBMISSIONS_BASE_URL',
  process.env.SUBMISSIONS_BASE_URL,
  API_BASE_URL,
);

// --- Observability (crash/perf reporting) config (MOB-018) -----------------
//
// Firebase Crashlytics + Performance Monitoring reuse the SAME
// `firebaseConfigPresent` gate as App Check above (both need the same
// GoogleService-Info.plist / google-services.json — MOB-010's human gate,
// not a new one). Until that gate clears, `expo prebuild` runs cleanly with
// no crash/perf plugin added and the client degrades gracefully (see
// src/observability/native-bridge.ts — same guarded-require pattern as
// src/security/app-check.ts). Do NOT fabricate a placeholder credential file
// to "turn this on".
//
// Kill switch + sampling (MOB-018 items 6/7): `observabilityEnabled`
// defaults to true and is override-able per build without a code change;
// `performanceSampleRate` bounds perf-trace volume (see
// src/observability/README.md "Sampling & retention" for the rationale).
// Crashlytics/Performance are free-tier / not billed per-event in Firebase's
// pricing model (unlike Firestore reads or a paid map API), so unlike
// `infra/gcp/cost-controls/cost-controls-matrix.json`'s metered-service
// budgets, there is no spend ceiling to enforce here — this is a
// volume/noise control plus a blunt off-switch, consistent with that same
// budget-capped/kill-switch operating posture.
const OBSERVABILITY_ENABLED = process.env.OBSERVABILITY_ENABLED === 'false' ? false : true;
const PERFORMANCE_SAMPLE_RATE = resolveSampleRate(process.env.PERFORMANCE_SAMPLE_RATE);

// App Check enforcement STAGE (MOB-010; ADR-020 §3 monitor→enforce rollout).
// Deliberately defaults to `monitor` — never hardcode `enforce`. Promotion is
// an explicit operational cutover (see src/security/README.md), overridable
// per-build via APP_CHECK_ENFORCEMENT_MODE but never to `enforce` by default.
const APP_CHECK_ENFORCEMENT_MODE = resolveEnforcementModeEnv(
  process.env.APP_CHECK_ENFORCEMENT_MODE,
);

// --- EAS Update / OTA (MOB-019, repo-ovn7; ADR-023 §2/§7, threat-model T6) -----
//
// `expo-updates` is installed (this bead's fix for ADR-023's amendment #2 — it
// was previously entirely absent). It stays STRUCTURALLY INERT until a real EAS
// project is provisioned (mobile-identity.md human gate #3 — no Expo/EAS
// organization exists yet): `updates.url` / `extra.eas.projectId` are gated on
// `EAS_PROJECT_ID`, following the same guarded-slot pattern as the Firebase
// config above. With no `updates.url`, `expo-updates` reports `Updates.isEnabled
// === false` and never attempts a network check — safe-by-default, not a
// silent no-op someone has to notice. Once `eas init`/`eas update:configure`
// runs for a real project, set `EAS_PROJECT_ID` per build profile in `eas.json`
// (or CI env) and this slot activates with no code change.
//
// `runtimeVersion: { policy: 'appVersion' }` is NOT gated — it is the
// structural boundary (ADR-023 §2) that rejects an incompatible OTA bundle
// client-side rather than shipping a crash, and costs nothing to declare ahead
// of the EAS project existing.
const EAS_PROJECT_ID = process.env.EAS_PROJECT_ID;

const config: ExpoConfig = {
  name: appName,
  // EAS project slug placeholder — no Expo/EAS organization has been
  // provisioned yet (mobile-identity.md human gate #3). This slug becomes
  // meaningful only once a real EAS project is linked (`eas init`); it
  // creates no store or EAS resource by itself.
  slug: 'blackstory-mobile',
  version: '1.0.0',
  orientation: 'portrait',
  // Custom URL scheme fallback per mobile-identity.md: `blackstory://`,
  // deliberately distinct from the reverse-DNS bundle id for readability in
  // support docs/marketing. Universal links / associated domains
  // (`blackbook.app`) are deferred to MOB-008/MOB-020 per that doc.
  scheme: 'blackstory',
  userInterfaceStyle: 'automatic',
  // EAS Update runtime-compatibility fence (ADR-023 §2): a JS bundle only ever
  // installs onto a binary whose runtime version matches, so an OTA update
  // built for an incompatible native layer is rejected client-side rather than
  // shipped and crashed. `appVersion` policy derives the runtime version from
  // the semantic app version above, so a native-affecting release (which must
  // bump `version`) automatically fences its OTA channel from older binaries
  // with no separate bookkeeping.
  runtimeVersion: {
    policy: 'appVersion',
  },
  // Gated on `EAS_PROJECT_ID` — see the comment above `EAS_PROJECT_ID`. Absent
  // today (no EAS project provisioned), so `expo-updates` has no update server
  // to poll and stays inert.
  ...(EAS_PROJECT_ID
    ? { updates: { url: `https://u.expo.dev/${EAS_PROJECT_ID}` } }
    : {}),
  // No `newArchEnabled` toggle: SDK 56 has fully removed the legacy
  // architecture, so New Architecture is the only supported mode and the
  // config field no longer exists (confirmed against
  // @expo/config-types@ExpoConfig for this SDK).
  icon: './assets/images/icon.png',
  ios: {
    // Native minimum OS floor per ADR-020 SS7, re-verified at this scaffold
    // (MOB-006) as that section requires: SDK 56's actual iOS platform
    // minimum is 16.4 (raised from SDK 54's ~15.1, per `pod install`
    // evidence — several Expo-bundled pods, including `expo` itself,
    // require iOS 16.4), which is *above* ADR-020's proposed 16.0 floor. Per
    // ADR-020 SS7 ("whichever SDK MOB-006 actually pins governs"), the
    // platform floor now governs: 16.4, not the originally proposed 16.0.
    deploymentTarget: '16.4',
    bundleIdentifier,
    icon: './assets/expo.icon',
    // MOB-010: the `@react-native-firebase/app` config plugin (added to
    // `plugins` below, gated on `firebaseConfigPresent`) copies this file
    // into the native project. Keyed by APP_VARIANT via the env var, which
    // EAS sets per-profile to the correct dev/preview/prod plist once the
    // Firebase apps are registered (mobile-identity.md gates #1/#3). No
    // Firebase config file is committed by this bead; do not fabricate one —
    // when the env var is unset (today) the plugin is not added and prebuild
    // runs cleanly with App Check absent.
    ...(GOOGLE_SERVICES_INFO_PLIST
      ? { googleServicesFile: GOOGLE_SERVICES_INFO_PLIST }
      : {}),
    //
    // Universal Links (MOB-008, mobile-identity.md's URL-scheme section, threat-model T4
    // "Universal-link domain binding"): declares this app as the handler for
    // https://blackbook.app/* links, verified by iOS against the real
    // apple-app-site-association file served from that domain's /.well-known/ path. Only
    // production points at the bare production domain; dev/preview builds never claim it
    // (avoids a dev build racing production for the same verified domain on a shared test
    // device). The AASA file itself is a local template only — see
    // apps/mobile/public/.well-known/README.md for what's real vs. templated, and
    // mobile-identity.md's open human gates (#1: Apple Team ID) for what's still missing
    // before this can be verified/published for real.
    associatedDomains: APP_VARIANT === 'production' ? ['applinks:blackbook.app'] : [],
  },
  android: {
    // Native minimum OS floor per ADR-020 SS7: Android 8.0 (API 26)+.
    package: bundleIdentifier,
    adaptiveIcon: {
      backgroundColor: '#E6F4FE',
      foregroundImage: './assets/images/android-icon-foreground.png',
      backgroundImage: './assets/images/android-icon-background.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
    // MOB-010: `@react-native-firebase/app` plugin (gated on
    // `firebaseConfigPresent` below) copies this google-services.json into the
    // Android project, keyed by APP_VARIANT via the env var. Not committed
    // here; the plugin is skipped entirely when the env var is unset (today).
    ...(GOOGLE_SERVICES_JSON ? { googleServicesFile: GOOGLE_SERVICES_JSON } : {}),
    //
    // Android App Links (MOB-008), the Android analogue of iOS associatedDomains above:
    // autoVerify asks Android to verify this app against the real assetlinks.json served
    // from https://blackbook.app/.well-known/assetlinks.json before treating the app as the
    // default handler for that host — see apps/mobile/public/.well-known/README.md for
    // what's templated vs. real (this needs a real Android signing SHA-256, mobile-identity.md
    // human gate #2, which doesn't exist yet). Production-only, same rationale as iOS.
    intentFilters:
      APP_VARIANT === 'production'
        ? [
            {
              action: 'VIEW',
              autoVerify: true,
              data: [{ scheme: 'https', host: 'blackbook.app' }],
              category: ['BROWSABLE', 'DEFAULT'],
            },
          ]
        : [],
  },
  web: {
    output: 'static',
    favicon: './assets/images/favicon.png',
  },
  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        backgroundColor: '#208AEF',
        image: './assets/images/splash-icon.png',
        imageWidth: 76,
      },
    ],
    // ADR-024 (MOB-011, corrected 2026-07-20) / repo-umwk: the official
    // `@maplibre/maplibre-react-native` config plugin (its own
    // `app.plugin.js` -> `withMapLibre`, NOT a bespoke plugin authored in
    // this repo). It injects `$MLRN.post_install(installer)` into the iOS
    // Podfile and the matching Gradle properties on Android at `expo
    // prebuild` time. No props are passed — the package's documented
    // defaults (native MapLibre distribution version pinned to this SDK
    // release, OpenGL Android location engine) match ADR-020/ADR-024's
    // renderer choice with no override needed.
    '@maplibre/maplibre-react-native',
    [
      // Enforces the Android API-level floor (ADR-020 SS7); iOS's floor is
      // set directly via `ios.deploymentTarget` above (a native ExpoConfig
      // field with no plugin needed).
      'expo-build-properties',
      {
        android: {
          minSdkVersion: 26,
        },
        ios: {
          // MOB-010 / ADR-020 §"USE_FRAMEWORKS=static": React Native Firebase
          // (App Check) REQUIRES static frameworks linkage, and the ADR-020
          // spike proved `pod install` succeeds with `USE_FRAMEWORKS=static`.
          // repo-umwk (ADR-024 "Deferred"/build gate) reconciles the SAME
          // requirement for `@maplibre/maplibre-react-native`'s official
          // config plugin (registered below) — its `withPodfilePostInstall`
          // step assumes/works under static frameworks, so one shared
          // `useFrameworks: 'static'` here satisfies both native deps rather
          // than each plugin racing to set it. Carrying it forward here (the
          // CNG source of truth) makes every `expo prebuild` emit
          // `ios.useFrameworks=static` into Podfile.properties.json so the
          // App Check pods and MapLibre pods both link correctly.
          useFrameworks: 'static',
        },
      },
    ],
    // MOB-010: App Check attestation plugins (ADR-020 §3 — App Attest /
    // DeviceCheck on iOS, Play Integrity on Android; NOT the web reCAPTCHA
    // provider). Wired into a SLOT that activates only when real Firebase
    // config files are supplied via env (`firebaseConfigPresent`). The
    // `@react-native-firebase/app` plugin throws at prebuild without a real
    // config file, so it is intentionally absent until the human gate clears.
    // The App Check native module itself is autolinked from package.json
    // regardless; these plugins only wire the AppDelegate init + config-file
    // copy that need a registered Firebase app to be meaningful.
    ...(firebaseConfigPresent
      ? [
          '@react-native-firebase/app',
          '@react-native-firebase/app-check',
          // MOB-018: Crashlytics + Performance Monitoring config plugins.
          // Same gate as App Check above (`firebaseConfigPresent`) — both
          // plugins need the same registered Firebase app + config file and
          // would otherwise throw at prebuild. Not a new human gate; reuses
          // MOB-010's. The native modules are autolinked from package.json
          // regardless; these plugins wire the dSYM/mapping-file upload
          // build phases (iOS Crashlytics) and Gradle plugin (Android) that
          // need a registered Firebase app to be meaningful.
          '@react-native-firebase/crashlytics',
          '@react-native-firebase/perf',
        ]
      : []),
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
  extra: {
    appVariant: APP_VARIANT,
    // API origins read at runtime by src/security/bootstrap.ts
    // (`createDefaultApiClient`) and src/features/corrections/runtime.ts
    // (`resolveSubmissionsBaseUrl`). Non-secret public hosts, validated above
    // (https required for production). Set per EAS profile via eas.json `env`.
    apiBaseUrl: API_BASE_URL,
    submissionsBaseUrl: SUBMISSIONS_BASE_URL,
    // Public Firebase project identifier + a JS-visible "is a real Firebase app
    // wired?" flag for diagnostics (does not import a native module). The real
    // credential is the GoogleService file copied by the config plugin, not
    // this object — see the App Check / Firebase section above.
    firebase: {
      projectId: FIREBASE_PROJECT_ID,
      configPresent: firebaseConfigPresent,
    },
    // App Check enforcement stage read at runtime by src/security/bootstrap.ts
    // (client-advisory only; server stays authoritative). Defaults to
    // `monitor` — see the cutover runbook in src/security/README.md.
    appCheckEnforcementMode: APP_CHECK_ENFORCEMENT_MODE,
    // MOB-018: observability kill switch + perf-trace sample rate, read at
    // runtime by src/observability/bootstrap.ts's `resolveObservabilityConfig`.
    // Defaults to enabled/10% — see src/observability/README.md.
    observabilityEnabled: OBSERVABILITY_ENABLED,
    performanceSampleRate: PERFORMANCE_SAMPLE_RATE,
    // `eas.projectId` (required by `expo-updates` to resolve its update
    // server) is gated on `EAS_PROJECT_ID` — see the comment above that
    // constant. No EAS organization/project is provisioned yet
    // (mobile-identity.md human gate #3); do not hand-write a fake project id
    // here. `eas init` / `eas update:configure` populate the real value once
    // that gate clears.
    ...(EAS_PROJECT_ID ? { eas: { projectId: EAS_PROJECT_ID } } : {}),
  },
};

export default config;
