// Generate EDIT-TIMELINE.md and CAPTURE-MANIFEST.md from the actual shot specs,
// capture manifest and marker map, so the documents cannot drift from the edit.
import fs from 'node:fs';
import path from 'node:path';
import { SHOTS, TOTAL } from './shots.mjs';

const ROOT = path.resolve('..');
const CAP = path.join(ROOT, 'captures');
const FPS = 60000 / 1001;
const manifest = JSON.parse(fs.readFileSync(path.join(CAP, 'manifest.json')));
const markers = JSON.parse(fs.readFileSync(path.join(ROOT, 'audio', 'markers.json')));

const tc = (f) => {
  const s = f / FPS;
  const m = Math.floor(s / 60),
    sec = s - m * 60;
  return `${String(m).padStart(2, '0')}:${sec.toFixed(3).padStart(6, '0')}`;
};
const timeline = SHOTS.filter((s) => s.name !== 'brand-fg');

// ---------------- EDIT-TIMELINE.md ----------------
let t = `# EDIT-TIMELINE

Authoritative edit decision list. Generated by \`project/write-docs.mjs\` from
\`project/shots.mjs\`, \`captures/manifest.json\` and \`audio/markers.json\` — it is
derived from the edit, not maintained alongside it.

- Frame rate: 59.94 fps (60000/1001)
- Total: ${TOTAL} frames = ${(TOTAL / FPS).toFixed(3)}s
- Audio starts at 0.0247s; the first frame of video is the first frame of audio.

## Shots

| # | In | Out | Frames | Dur | Surface | Action | Transition in | Audio event |
|---|---|---|---|---|---|---|---|---|
`;
timeline.forEach((s, i) => {
  const trans =
    i === 0
      ? 'from black (first frame)'
      : s.name === 'memorial-b'
        ? '5-frame dissolve'
        : s.name === 'tulsa-1921'
          ? 'hard cut (match cut)'
          : ['map-b', 'map-c', 'map-d'].includes(s.name)
            ? 'motion-matched join: camera launches on the hit (velocity punch)'
            : s.name === 'brand-bg'
              ? 'motion-matched join; scrim + lockup fade in'
              : 'hard cut';
  t += `| ${String(i + 1).padStart(2, '0')} | ${tc(s.in)} | ${tc(s.out)} | ${s.frames} | ${(s.frames / FPS).toFixed(3)}s | ${s.surface} | ${s.action} | ${trans} | ${s.audio ?? ''} |\n`;
});
t += `
Note: \`memorial-a\` and \`memorial-b\` are assembled as one continuous Memorial
passage (frames 1681–2529, 14.147s) joined by a 5-frame dissolve rather than a
cut. \`brand-fg\` is not a timeline row — it is an alpha layer composited over
\`brand-bg\` for frames 3074–3264.

## Movement and speed per shot

| # | Shot | Movement | Easing | Hold (silence) |
|---|---|---|---|---|
`;
const EASE = {
  'map-a': ['national drift east, zoom 4.26→4.46', 'inQuad', '—'],
  'map-b': ['zoom 4.46→5.80, pitch 0→18, bearing 0→-5', 'outQuart', '46f held (GAP 5.637)'],
  'map-c': ['zoom 5.80→8.60, pitch 18→34', 'outQuart', '51f held (GAP 8.613)'],
  'map-d': ['zoom 8.60→12.60, pitch 34→48', 'outQuart', '46f held (GAP 11.595)'],
};
timeline.forEach((s, i) => {
  const e = EASE[s.name];
  t += `| ${String(i + 1).padStart(2, '0')} | ${s.name} | ${e ? e[0] : s.needsMap ? 'map camera move' : 'document camera pan/push'} | ${e ? e[1] : 'authored per shot (see shots.mjs)'} | ${e ? e[2] : '—'} |\n`;
});

t += `\n## Audio markers\n\nFull set in \`audio/markers.json\`. The markers the edit cuts on:\n\n`;
const cutFrames = new Set(timeline.map((s) => s.in));
t += `| Marker | Time | Frame | Kind | Strength | Cut here |\n|---|---|---|---|---|---|\n`;
const near = markers.markers.filter(
  (m) =>
    [...cutFrames].some((f) => Math.abs(f - m.frame) <= 3) ||
    m.kind === 'GAP' ||
    (m.kind === 'VOX' && m.sustain > 1.5) ||
    (m.kind === 'HIT' && m.strength > 0.78),
);
near.forEach((m, i) => {
  t += `| M${String(i + 1).padStart(3, '0')} | ${m.t.toFixed(3)}s | ${m.frame} | ${m.kind}${m.kind === 'VOX' ? ` (sustain ${m.sustain}s)` : ''} | ${m.strength} | ${[...cutFrames].some((f) => Math.abs(f - m.frame) <= 3) ? 'yes' : ''} |\n`;
});
fs.writeFileSync(path.join(ROOT, 'EDIT-TIMELINE.md'), t);

// ---------------- CAPTURE-MANIFEST.md ----------------
let c = `# CAPTURE-MANIFEST

Every capture used in the edit. Generated by \`project/write-docs.mjs\`.

- Capture viewport: 1080×1920 CSS px at deviceScaleFactor 2 → 2160×3840 captured,
  downscaled to 1080×1920 with lanczos (supersampled, not resampled).
- Frame rate: 59.94 fps. Captures are deterministic frame renders, not recordings.
- Source: local dev server \`http://localhost:3048\` (Postgres-backed, live
  \`published\` data). See DECISIONS.md §D4 for why not production.
- Every capture carries handle frames at both ends beyond its edit length.

`;
for (const s of SHOTS) {
  const m = manifest[s.name];
  if (!m) {
    c += `## ${s.name}\n\n**NOT CAPTURED**\n\n`;
    continue;
  }
  c += `## ${m.file}

| | |
|---|---|
| URL | \`${s.url.replace('http://localhost:3048', '')}\` |
| Surface | ${s.surface} |
| Action | ${s.action} |
| Capture resolution | 2160×3840 → 1080×1920 |
| FPS | 59.94 |
| Frames | ${m.frames} edit + ${m.handle} handle each end = ${m.totalFrames} |
| Duration (edit length) | ${(m.frames / FPS).toFixed(3)}s |
| Captured | ${m.capturedAt?.slice(0, 19).replace('T', ' ')} |
| Used in final cut | ${s.name === 'brand-fg' ? 'yes (alpha overlay)' : 'yes'} |
| Timeline position | ${tc(s.in)}–${tc(s.out)} |
| Audio event | ${s.audio ?? '—'} |
${m.errors?.length ? `| Page errors | ${m.errors.length} (non-fatal) |\n` : ''}
`;
}
fs.writeFileSync(path.join(ROOT, 'CAPTURE-MANIFEST.md'), c);
console.error('wrote EDIT-TIMELINE.md and CAPTURE-MANIFEST.md');
