/**
 * Authored Lives world beats. Sparse by design: high-quality count, policy, testimony, and
 * insufficient_evidence off-ramps across decades. Auto gap cards fill core domains that still lack
 * a beat. Citations are Tier-1 or opened primary sources. Method:
 * docs/methodology/lives-across-decades.md and docs/research/lives-gap-and-sourcing.md.
 */
import type { LivesWorldBeatInput } from '@repo/domain/statistics/lives';

export const LIVES_WORLD_BEAT_FIXTURES: readonly LivesWorldBeatInput[] = [
  {
    id: '1870-housing-fountain-hughes',
    decade: 1870,
    areaIds: [],
    lenses: ['black'],
    unit: 'all',
    domain: 'housing',
    claimType: 'testimony',
    heading: 'After freedom, no home to go to',
    body: 'Fountain Hughes was recorded in Baltimore on June 11, 1949, by Hermond Norwood, a Library of Congress engineer. Hughes said he was born in Charlottesville, Virginia, and gave his age as 101. He described the years just after freedom: children bound out to different people, running away from them, and sleeping wherever he and his brother could, one night inside a vehicle in a man’s livery stable yard.',
    quote: 'We didn’t have no property. We didn’t have no home. We had nowhere or nothing.',
    citations: [
      {
        label:
          'Interview with Fountain Hughes, Baltimore, Maryland, June 11, 1949. American Folklife Center, Library of Congress (AFC 1950/037: AFS 09990A)',
        url: 'https://www.loc.gov/item/afc1950037_afs09990a/',
      },
      {
        label:
          'Library of Congress, Voices Remembering Slavery: Freed People Tell Their Stories, About this Collection',
        url: 'https://www.loc.gov/collections/voices-remembering-slavery/about-this-collection/',
      },
    ],
    entityIds: [],
    speaker: {
      name: 'Fountain Hughes',
      place: 'Baltimore, Maryland',
      year: 'recorded 1949, recalling the late 1860s and after',
      mediation: 'recorded-interview',
      mediatedBy: 'Hermond Norwood',
    },
    recording: {
      mediaUrl:
        'https://tile.loc.gov/storage-services/service/afc/afc1950037/afc1950037_afs09990/afc1950037_afs09990a.mp3',
      itemUrl: 'https://www.loc.gov/item/afc1950037_afs09990a/',
      transcriptUrl:
        'https://tile.loc.gov/storage-services/service/afc/afc1950037/afc1950037_afs09990/afc1950037_afs09990a.pdf',
      holdingInstitution: 'the Library of Congress',
      creditLine:
        'Cyrus B. Koonce Collection (AFC 1950/037), American Folklife Center, Library of Congress',
      rightsNote:
        'The Library of Congress says it is unaware of any copyright or other restrictions in this collection.',
      recordedOn: 'June 11, 1949, in Baltimore, Maryland',
      contentNote:
        'This recording carries the language of its time, and Hughes describes life in slavery.',
    },
  },
  {
    id: '1870-count-reconstruction',
    decade: 1870,
    areaIds: [],
    lenses: ['black', 'all'],
    unit: 'all',
    domain: 'count',
    claimType: 'factual',
    heading: 'The first post-war census',
    body: 'The 1870 census is the first after emancipation. Literacy and school attendance by race enter the printed volumes; class for this decade is still work-based, not income. Hispanic origin isn’t counted.',
    citations: [
      {
        label: 'Census Bureau, Ninth Census volumes (1870)',
        url: 'https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1870.html',
      },
    ],
    entityIds: [],
  },
  {
    id: '1870-policy-amendments',
    decade: 1870,
    areaIds: [],
    lenses: ['black', 'all'],
    unit: 'all',
    domain: 'policy',
    claimType: 'factual',
    heading: 'Reconstruction amendments in force',
    body: 'The Thirteenth, Fourteenth, and Fifteenth Amendments sit in the catalog beside 1870s figures. Showing them with literacy shares doesn’t prove they caused those shares.',
    citations: [
      {
        label: 'National Archives, Reconstruction Amendments',
        url: 'https://www.archives.gov/milestone-documents/13th-amendment',
      },
    ],
    entityIds: [],
    uncertaintyLabel: 'Juxtaposition only until a gated causal claim is attached.',
  },
  {
    id: '1910-count-great-migration-eve',
    decade: 1910,
    areaIds: [],
    lenses: ['black', 'all'],
    unit: 'all',
    domain: 'count',
    claimType: 'factual',
    heading: 'Urban shares on the eve of the Great Migration',
    body: 'Table 42 and the 1918 Negro Population bulletin publish urban and rural Negro and white populations by state for 1890–1910. Those shares are region figures when states sum; they aren’t a single city’s rate.',
    citations: [
      {
        label: 'Census Bureau, Negro Population 1790–1915 (1918)',
        url: 'https://www.census.gov/library/publications/1918/dec/negro-population-1790-1915.html',
      },
    ],
    entityIds: [],
  },
  {
    id: '1910-testimony-northeast-harlem',
    decade: 1910,
    areaIds: ['region:us-northeast'],
    lenses: ['black'],
    unit: 'household',
    domain: 'testimony',
    claimType: 'testimony',
    heading: 'A named Northern city voice',
    body: 'James Weldon Johnson’s Black Manhattan (1930) looks back on Harlem’s early century. The speaker is named; Northeast urban shares beside him remain the census’s state sums, not Harlem’s rate.',
    citations: [
      {
        label: 'James Weldon Johnson, Black Manhattan (1930)',
        url: 'https://www.loc.gov/item/30011254/',
      },
    ],
    entityIds: [],
    speaker: {
      name: 'James Weldon Johnson',
      place: 'New York',
      year: '1910s recalled',
      classNote: 'Writer and NAACP organizer',
      mediation: 'self-authored',
    },
  },
  {
    id: '1910-testimony-midwest-bronzeville',
    decade: 1910,
    areaIds: ['region:us-midwest'],
    lenses: ['black'],
    unit: 'household',
    domain: 'testimony',
    claimType: 'testimony',
    heading: 'Migration into the Midwest',
    body: 'Richard Wright’s Black Boy (1945) and later Chicago writing name the pull of Northern industrial cities. Midwest figures stay state sums; Bronzeville illustrates, it doesn’t replace the region.',
    citations: [
      {
        label: 'Richard Wright, Black Boy (1945)',
        url: 'https://www.loc.gov/item/45002087/',
      },
    ],
    entityIds: [],
    speaker: {
      name: 'Richard Wright',
      place: 'Mississippi and Chicago, Illinois',
      year: '1910s–1920s recalled',
      classNote: 'Childhood South, young adulthood Midwest',
      mediation: 'self-authored',
    },
  },
  {
    id: '1930-count-mexican-category',
    decade: 1930,
    areaIds: [],
    lenses: ['hispanic', 'all'],
    unit: 'all',
    domain: 'count',
    claimType: 'factual',
    heading: 'Mexican as a race in 1930',
    body: 'The 1930 census counted "Mexican" as a race for one decade, then removed the category. Hispanic origin as asked from 1970 on isn’t the same count. The gap is content, not a missing cell to invent.',
    citations: [
      {
        label: 'Census Bureau, Fifteenth Census Population volumes (1930)',
        url: 'https://www.census.gov/library/publications/1930/dec/population-volume-1.html',
      },
    ],
    entityIds: [],
  },
  {
    id: '1930-housing-deep-south',
    decade: 1930,
    areaIds: ['region:us-deep-south'],
    lenses: ['black'],
    unit: 'household',
    domain: 'housing',
    claimType: 'factual',
    heading: 'Tenure on the printed page',
    body: 'The 1930 census published home value and contract rent by race at state level. Those tables are the affordance inputs for this decade, not HOLC grades, which never become Lives region cells.',
    citations: [
      {
        label: 'Census Bureau, Negroes in the United States, 1920–32 (1935)',
        url: 'https://www2.census.gov/library/publications/1935/decennial/negroes-in-the-united-states-1920-1932.pdf',
      },
    ],
    entityIds: [],
  },
  {
    id: '1930-policy-nlra',
    decade: 1930,
    areaIds: [],
    lenses: ['all'],
    unit: 'all',
    domain: 'policy',
    claimType: 'factual',
    heading: 'Labor law arriving at mid-decade',
    body: 'The National Labor Relations Act (1935) sits in the catalog beside 1930s figures. Showing it with class shares doesn’t prove it caused those shares. Agricultural and domestic exclusions remain a live dispute in the record.',
    citations: [
      {
        label: 'National Labor Relations Act, 49 Stat. 449 (1935)',
        url: 'https://www.govinfo.gov/content/pkg/STATUTE-49/pdf/STATUTE-49-Pg449.pdf',
      },
    ],
    entityIds: ['ent_law_national_labor_relations_act_1935'],
    uncertaintyLabel: 'Juxtaposition only until a gated causal claim is attached.',
  },
  {
    id: '1930-work-unions',
    decade: 1930,
    areaIds: [],
    lenses: ['black', 'all'],
    unit: 'woman',
    domain: 'work',
    claimType: 'interpretive',
    heading: 'Women in gainful occupations',
    body: 'Occupation volumes from 1900 onward cross sex and color. The woman unit reads those tables; household income isn’t relabeled as her wage.',
    citations: [
      {
        label: 'Census Bureau, Occupations at the Twelfth Census (1904)',
        url: 'https://www2.census.gov/library/publications/decennial/1900/occupations/1900-census-occupations-toc.pdf',
      },
    ],
    entityIds: [],
  },
  {
    id: '1930-testimony-sharecropping',
    decade: 1930,
    areaIds: ['region:us-deep-south'],
    lenses: ['black'],
    unit: 'household',
    domain: 'testimony',
    claimType: 'testimony',
    heading: 'A named voice from the cotton South',
    body: "Nate Shaw (Ned Cobb), an Alabama tenant farmer, told Theodore Rosengarten a life of farm labor, debt, and organizing under tenancy. The memoir is his testimony; the region figures beside it are the census's.",
    citations: [
      {
        label: "Theodore Rosengarten, All God's Dangers: The Life of Nate Shaw (1974)",
        url: 'https://www.loc.gov/item/74003447/',
      },
    ],
    entityIds: [],
    speaker: {
      name: 'Nate Shaw (Ned Cobb)',
      place: 'Alabama',
      year: '1930s',
      classNote: 'Tenant farmer',
      mediation: 'as-told-to',
      mediatedBy: 'Theodore Rosengarten',
    },
  },
  {
    id: '1930-world-depression',
    decade: 1930,
    areaIds: [],
    lenses: ['all'],
    unit: 'all',
    domain: 'world',
    claimType: 'factual',
    heading: 'Depression on the published tables',
    body: "Unemployment by race appears in the 1930 census. The decade's laws and relief programs open as catalog records; the street doesn’t invent a bread line density from those laws.",
    citations: [
      {
        label: 'Census Bureau, Fifteenth Census unemployment reports',
        url: 'https://www.census.gov/library/publications/1930/dec/population-volume-2.html',
      },
    ],
    entityIds: [],
  },
  {
    id: '1930-testimony-west-mexican',
    decade: 1930,
    areaIds: ['region:us-west', 'region:us-texas-oklahoma'],
    lenses: ['hispanic', 'all'],
    unit: 'household',
    domain: 'testimony',
    claimType: 'testimony',
    heading: 'A named Southwest voice under the Mexican category',
    body: 'Carey McWilliams’s North from Mexico (1948) documents Mexican American communities in the Southwest under the one-decade “Mexican” race count. West and Texas–Oklahoma figures stay published tables; East LA and San Antonio illustrate.',
    citations: [
      {
        label: 'Carey McWilliams, North from Mexico (1948)',
        url: 'https://www.loc.gov/item/48006491/',
      },
    ],
    entityIds: [],
    speaker: {
      name: 'Carey McWilliams',
      place: 'California',
      year: '1930s reported',
      classNote: 'Journalist and advocate',
      mediation: 'reported-by-third-party',
    },
  },
  {
    id: '1940-count-wage-income',
    decade: 1940,
    areaIds: [],
    lenses: ['all'],
    unit: 'household',
    domain: 'count',
    claimType: 'factual',
    heading: 'Wages enter the census',
    body: '1940 is the first census with wage and salary income. Farm, business, and other income are out of those bands. Class for this decade is wage-based, not the work-based regime of 1870–1930.',
    citations: [
      {
        label: 'Census Bureau, Sixteenth Census Population volumes (1940)',
        url: 'https://www.census.gov/programs-surveys/decennial-census/decade/decennial-publications.1940.html',
      },
    ],
    entityIds: [],
  },
  {
    id: '1940-policy-fair-labor',
    decade: 1940,
    areaIds: [],
    lenses: ['black', 'all'],
    unit: 'all',
    domain: 'policy',
    claimType: 'factual',
    heading: 'Fair Labor Standards Act beside the tables',
    body: 'The Fair Labor Standards Act (1938) is in force for this decade. Agricultural and domestic exclusions again sit next to wage bands without proving causation.',
    citations: [
      {
        label: 'Fair Labor Standards Act, 52 Stat. 1060 (1938)',
        url: 'https://www.govinfo.gov/content/pkg/STATUTE-52/pdf/STATUTE-52-Pg1060.pdf',
      },
    ],
    entityIds: [],
    uncertaintyLabel: 'Juxtaposition only until a gated causal claim is attached.',
  },
  {
    id: '1960-school-brown-aftermath',
    decade: 1960,
    areaIds: [],
    lenses: ['black'],
    unit: 'child',
    domain: 'schooling',
    claimType: 'factual',
    heading: 'School after Brown',
    body: 'High school completion by race enters the printed volumes in mid-century. Brown v. Board (1954) is in force as law for this decade; the attainment bars aren’t labeled as its effect.',
    citations: [
      {
        label: 'Brown v. Board of Education, 347 U.S. 483 (1954)',
        url: 'https://tile.loc.gov/storage-services/service/ll/usrep/usrep347/usrep347483/usrep347483.pdf',
      },
    ],
    entityIds: [],
  },
  {
    id: '1960-housing-fair-housing-path',
    decade: 1960,
    areaIds: [],
    lenses: ['black'],
    unit: 'household',
    domain: 'housing',
    claimType: 'factual',
    heading: 'Tenure before Fair Housing',
    body: 'Homeownership by race is published for this decade. The Fair Housing Act arrives in 1968; HOLC maps are an off-ramp into theme-impact, never a Lives region rate.',
    citations: [
      {
        label: 'Census of Housing, 1960, Vol. I',
        url: 'https://www.census.gov/library/publications/1960/dec/housing-volume-1.html',
      },
    ],
    entityIds: [],
  },
  {
    id: '1960-political-voting',
    decade: 1960,
    areaIds: [],
    lenses: ['black'],
    unit: 'all',
    domain: 'political',
    claimType: 'factual',
    heading: 'Ballot access under literacy tests',
    body: 'Literacy tests and poll taxes sit in the catalog as voting-domain rules. The Voting Rights Act of 1965 is in force for later years of this decade; turnout isn’t invented as a Lives region cell.',
    citations: [
      {
        label: 'Voting Rights Act of 1965, 79 Stat. 437',
        url: 'https://www.govinfo.gov/content/pkg/STATUTE-79/pdf/STATUTE-79-Pg437.pdf',
      },
    ],
    entityIds: ['ent_law_voting_rights_act_1965'],
  },
  {
    id: '1960-justice-offramp',
    decade: 1960,
    areaIds: [],
    lenses: ['black'],
    unit: 'all',
    domain: 'justice',
    claimType: 'factual',
    gapState: 'insufficient_evidence',
    heading: 'No crime heat on this street',
    body: 'Imprisonment and victimization series open on Data (/data#justice-imprisonment) and theme-impact when published by race. This decade doesn’t hatch a police-stop density from missing tables.',
    citations: [
      {
        label: 'Data · Justice imprisonment spine',
        url: '/data#justice-imprisonment',
      },
      {
        label: 'Bureau of Justice Statistics, National Prisoner Statistics',
        url: 'https://bjs.ojp.gov/data-collection/nps',
      },
    ],
    entityIds: [],
    uncertaintyLabel: 'Insufficient evidence for a Lives region justice rate in this decade.',
  },
  {
    id: '1960-world-vietnam',
    decade: 1960,
    areaIds: [],
    lenses: ['all'],
    unit: 'all',
    domain: 'world',
    claimType: 'factual',
    heading: 'War and draft in the catalog',
    body: 'Vietnam-era service and draft policy open as people, laws, and stories. Draft isn’t a region rate on the Lives street.',
    citations: [
      {
        label: 'National Archives, Vietnam War records',
        url: 'https://www.archives.gov/research/military/vietnam-war',
      },
    ],
    entityIds: [],
  },
  {
    id: '1960-testimony-angelou',
    decade: 1960,
    areaIds: ['region:us-deep-south', 'region:us-upper-south'],
    lenses: ['black'],
    unit: 'child',
    domain: 'testimony',
    claimType: 'testimony',
    heading: 'A childhood named in print',
    body: "Maya Angelou's I Know Why the Caged Bird Sings (1969) recounts a childhood in Stamps, Arkansas, under segregation. The speaker is named; the region figures remain the census's.",
    citations: [
      {
        label: 'Maya Angelou, I Know Why the Caged Bird Sings (1969)',
        url: 'https://www.loc.gov/item/69016407/',
      },
    ],
    entityIds: [],
    speaker: {
      name: 'Maya Angelou',
      place: 'Stamps, Arkansas',
      year: '1930s–1940s recalled',
      classNote: 'Childhood in the Upper South / Deep South border',
      mediation: 'self-authored',
    },
  },
  {
    id: '1960-health-nchs-offramp',
    decade: 1960,
    areaIds: [],
    lenses: ['all'],
    unit: 'all',
    domain: 'health',
    claimType: 'factual',
    gapState: 'insufficient_evidence',
    heading: 'National life expectancy, not a region cell',
    body: 'NCHS life-expectancy series are a national off-ramp, not a Lives region cell. Open Data gaps for related national spines, Methodology for how Lives refuses invented mortality rates, and Stories or Books for named testimony.',
    citations: [
      {
        label: 'Data · Measured gaps',
        url: '/data#gaps',
      },
      {
        label: 'Methodology · Lives across the decades',
        url: '/methodology#lives-across-decades',
      },
      {
        label: 'National Center for Health Statistics',
        url: 'https://www.cdc.gov/nchs/index.htm',
      },
      {
        label: 'Stories room',
        url: '/stories',
      },
      {
        label: 'Books room',
        url: '/books',
      },
    ],
    entityIds: [],
  },
  {
    id: '1970-count-spanish-origin',
    decade: 1970,
    areaIds: [],
    lenses: ['hispanic', 'all'],
    unit: 'all',
    domain: 'count',
    claimType: 'factual',
    heading: 'Spanish origin on a sample',
    body: '1970 asks Spanish origin of a sample. Hundreds of thousands in the South and central regions were misclassified as Central or South American. The sample-question decade is content, not a silent empty box.',
    citations: [
      {
        label: 'Pew Research Center, Census History: Counting Hispanics',
        url: 'https://www.pewresearch.org/social-trends/2010/03/03/census-history-counting-hispanics-2/',
      },
    ],
    entityIds: [],
  },
  {
    id: '1970-affordance-same-year',
    decade: 1970,
    areaIds: [],
    lenses: ['black', 'all'],
    unit: 'household',
    domain: 'affordance',
    claimType: 'modeled',
    gapState: 'modeled',
    heading: 'Rent against 1969 income when both exist',
    body: 'Modeled affordance uses same-year published rent or home value against same-year income for the same race slice. 1970 family medians (Table 83) restate with CPI. Same-year contract rent for Total and Negro head comes from HC(1)-A Tables 1 and 6.',
    citations: [
      {
        label: 'Methodology · Lives across the decades',
        url: '/methodology#lives-across-decades',
      },
      {
        label: '1970 PC(1)-C1 Table 83',
        url: 'https://www2.census.gov/library/publications/decennial/1970/population-volume-1/1970a_us1-10.pdf',
      },
      {
        label: '1970 HC(1)-A Tables 1 and 6',
        url: 'https://www2.census.gov/library/publications/decennial/1970/housing-volume-1/13276827v1p1ch01.pdf',
      },
    ],
    entityIds: [],
    uncertaintyLabel:
      'Modeled only when same-year income and rent or value are both published for the same group.',
  },
  {
    id: '1970-affordance-white-rent-gap',
    decade: 1970,
    areaIds: [],
    lenses: ['white'],
    unit: 'household',
    domain: 'affordance',
    claimType: 'factual',
    gapState: 'insufficient_evidence',
    heading: 'White contract rent isn’t in HC(1)-A',
    body: 'HC(1)-A Tables 1 and 6 print Total and Negro-head median contract rent and home value. They don’t print a White median. Lives doesn’t residualize White from Total minus Negro, so the white lens keeps derived income and leaves affordance as a gap until another published White table is opened.',
    citations: [
      {
        label: '1970 HC(1)-A Tables 1 and 6',
        url: 'https://www2.census.gov/library/publications/decennial/1970/housing-volume-1/13276827v1p1ch01.pdf',
      },
      {
        label: 'Methodology · Lives across the decades',
        url: '/methodology#lives-across-decades',
      },
    ],
    entityIds: [],
    uncertaintyLabel:
      'Insufficient evidence for a white-lens same-year rent affordance from HC(1)-A.',
  },
  {
    id: '1990-count-household-income',
    decade: 1990,
    areaIds: [],
    lenses: ['all'],
    unit: 'household',
    domain: 'count',
    claimType: 'factual',
    heading: 'Household income as the footing',
    body: 'From 1990 the long-form tables publish household income by race and Hispanic origin for states. Class bands sit against the national median of the same unit. Cross-regime change with family-income decades is refused.',
    citations: [
      {
        label: 'Census Bureau, 1990 Summary Tape File documentation',
        url: 'https://www.census.gov/data/datasets/1990/dec/stf.html',
      },
    ],
    entityIds: [],
  },
];
