/**
 * Storage path helpers for release catalog artifacts (CDN / public-media bucket). See
 * `docs/decisions-carryover.md`, "Public projection and immutable publication snapshots".
 * Kept free of `node:crypto` so Node and TypeScript consumers can import without the
 * publication signing surface.
 */

const SAFE_PATH_SEGMENT = /^[A-Za-z0-9][A-Za-z0-9._-]{0,255}$/;

function assertSafePathSegment(value: string, field: string): void {
  if (!SAFE_PATH_SEGMENT.test(value) || value === '.' || value === '..') {
    throw new Error(`${field} is not a safe storage path segment`);
  }
}

/**
 * Aggregate release catalog for map/list/history/sitemap (`docs/decisions-carryover.md`, "Public
 * projection and immutable publication snapshots"). One JSON object replaces an unbounded
 * released-entity table scan on the public web. This and
 * `search-index.json` are the only two of the eight paths in this file that a live publisher
 * actually writes.
 */
export function publicReleaseEntitiesListPath(releaseId: string): string {
  assertSafePathSegment(releaseId, 'releaseId');
  return `public/releases/${releaseId}/entities.json`;
}

/**
 * Aggregate search-index artifact for the public search surface (see
 * `docs/decisions-carryover.md`).
 * Prefer this (or `published.search_index` reads) over rebuilding the index from entity
 * projections at request time.
 */
export function publicReleaseSearchIndexPath(releaseId: string): string {
  assertSafePathSegment(releaseId, 'releaseId');
  return `public/releases/${releaseId}/search-index.json`;
}

/**
 * Aggregate map GeoJSON FeatureCollection artifact (`docs/decisions-carryover.md`,
 * "Map stack"). This is the release-coupled map source `buildMapSource` produces, with every
 * coordinate already passed through `redactLocationForPublic`. Generated by
 * `generateReleaseArtifacts` but not published by any live pipeline and read by nothing today;
 * see `workers/publication/MAP_SOURCE_INTEGRATION.md` and "Map stack": release-coupled build.
 */
export function publicReleaseMapSourcePath(releaseId: string): string {
  assertSafePathSegment(releaseId, 'releaseId');
  return `public/releases/${releaseId}/map/source.json`;
}

/** State-level presence aggregate for the map surface (`docs/decisions-carryover.md`,
 * "Map stack"). Generated with the release, not yet read by any surface. */
export function publicReleaseMapStateAggregatesPath(releaseId: string): string {
  assertSafePathSegment(releaseId, 'releaseId');
  return `public/releases/${releaseId}/map/state-aggregates.json`;
}

/** County-level presence aggregate for the map surface (`docs/decisions-carryover.md`,
 * "Map stack"). Populated only from explicit jurisdiction hints, never from a coordinate. */
export function publicReleaseMapCountyAggregatesPath(releaseId: string): string {
  assertSafePathSegment(releaseId, 'releaseId');
  return `public/releases/${releaseId}/map/county-aggregates.json`;
}

/**
 * Bounded flat-point artifact for offline map dots, sized so the mobile client can download it
 * once per release (`docs/decisions-carryover.md`, "Map stack": size budgets, and "Mobile cache
 * and OTA release" for the client-side byte ceiling that budget serves). Distinct from
 * `map/source.json` so a size/gzip budget can be enforced on the client-shipped payload
 * independently of the fuller web map source, and that budget (`DEFAULT_BOUNDED_POINTS_BUDGET`)
 * is the one release-time size gate that actually fires. The mobile client reads `GET /v1/map`
 * today, not this artifact.
 */
export function publicReleaseBoundedPointsPath(releaseId: string): string {
  assertSafePathSegment(releaseId, 'releaseId');
  return `public/releases/${releaseId}/map/bounded-points.json`;
}

/** Static-content index artifact (stories / methodology / learn) for the active release. */
export function publicReleaseContentIndexPath(releaseId: string): string {
  assertSafePathSegment(releaseId, 'releaseId');
  return `public/releases/${releaseId}/content/index.json`;
}

/**
 * Mobile cold-start bootstrap manifest artifact (MOB-005). One JSON object the `/v1/bootstrap`
 * handler in `apps/api-public` projects the active-release pointer from. Content-addressed like
 * every other release artifact so rollback restores the exact bootstrap the client last saw.
 */
export function publicReleaseBootstrapPath(releaseId: string): string {
  assertSafePathSegment(releaseId, 'releaseId');
  return `public/releases/${releaseId}/bootstrap.json`;
}
