/**
 * Versioned registry of stable theme ids and display labels. Named organizations, people and
 * individual events belong in entity references rather than theme facets. Bump the taxonomy
 * version when removing or renaming ids. Unknown ids are not taxonomy members.
 * Imported values require explicit classification before publication.
 */

export const TOPIC_TAXONOMY_SCHEMA_VERSION = 1;

export type TopicDefinition = {
  readonly id: string;
  readonly label: string;
  readonly schemaVersion: number;
};

const RAW_TOPIC_ENTRIES: ReadonlyArray<{ readonly id: string; readonly label: string }> = [
  { id: 'abolition', label: 'Abolition' },
  { id: 'affirmative-action', label: 'Affirmative Action' },
  { id: 'agriculture', label: 'Agriculture' },
  { id: 'air-force', label: 'Air Force' },
  { id: 'anti-miscegenation', label: 'Anti-Miscegenation' },
  { id: 'army', label: 'Army' },
  { id: 'archive', label: 'Archive' },
  { id: 'archives', label: 'Archives' },
  { id: 'architecture', label: 'Architecture' },
  { id: 'art', label: 'Art' },
  { id: 'arts', label: 'Arts' },
  { id: 'assassination', label: 'Assassination' },
  { id: 'aviation', label: 'Aviation' },
  { id: 'automotive', label: 'Automotive' },
  { id: 'banking', label: 'Banking' },
  { id: 'baseball', label: 'Baseball' },
  { id: 'basketball', label: 'Basketball' },
  { id: 'ballroom', label: 'Ballroom' },
  { id: 'biology', label: 'Biology' },
  { id: 'blues', label: 'Blues' },
  { id: 'birthplace', label: 'Birthplace' },
  { id: 'black-architects', label: 'Black Architects' },
  { id: 'black-codes', label: 'Black Codes' },
  { id: 'black-nationalism', label: 'Black Nationalism' },
  { id: 'black-power', label: 'Black Power' },
  { id: 'bobsled', label: 'Bobsled' },
  { id: 'boxing', label: 'Boxing' },
  { id: 'boyhood-home', label: 'Boyhood Home' },
  { id: 'business', label: 'Business' },
  { id: 'burial-ground', label: 'Burial Ground' },
  { id: 'busing', label: 'Busing' },
  { id: 'cabinet', label: 'Cabinet' },
  { id: 'chemistry', label: 'Chemistry' },
  { id: 'cemetery', label: 'Cemetery' },
  { id: 'childhood', label: 'Childhood' },
  { id: 'church', label: 'Church' },
  { id: 'citizenship', label: 'Citizenship' },
  { id: 'citizenship-schools', label: 'Citizenship Schools' },
  { id: 'civil-rights', label: 'Civil Rights' },
  { id: 'civil-war', label: 'Civil War' },
  { id: 'coalition', label: 'Coalition' },
  { id: 'commemoration', label: 'Commemoration' },
  { id: 'commerce-clause', label: 'Commerce Clause' },
  { id: 'community', label: 'Community' },
  { id: 'community-organizing', label: 'Community Organizing' },
  { id: 'community-programs', label: 'Community Programs' },
  { id: 'constitutional-law', label: 'Constitutional Law' },
  { id: 'cooperatives', label: 'Cooperatives' },
  { id: 'criminal-justice', label: 'Criminal Justice' },
  { id: 'craft', label: 'Craft' },
  { id: 'culture', label: 'Culture' },
  { id: 'dance', label: 'Dance' },
  { id: 'denomination-founding', label: 'Denomination Founding' },
  { id: 'desegregation', label: 'Desegregation' },
  { id: 'debate', label: 'Debate' },
  { id: 'diplomacy', label: 'Diplomacy' },
  { id: 'domestic-work', label: 'Domestic Work' },
  { id: 'direct-action', label: 'Direct Action' },
  { id: 'disparate-impact', label: 'Disparate Impact' },
  { id: 'district', label: 'District' },
  { id: 'due-process', label: 'Due Process' },
  { id: 'economic-justice', label: 'Economic Justice' },
  { id: 'education', label: 'Education' },
  { id: 'emancipation', label: 'Emancipation' },
  { id: 'employment', label: 'Employment' },
  { id: 'engineering', label: 'Engineering' },
  { id: 'enslavement', label: 'Enslavement' },
  { id: 'entrepreneurship', label: 'Entrepreneurship' },
  { id: 'equal-protection', label: 'Equal Protection' },
  { id: 'eugenics', label: 'Eugenics' },
  { id: 'fair-housing', label: 'Fair Housing' },
  { id: 'federal-intervention', label: 'Federal Intervention' },
  { id: 'figure-skating', label: 'Figure Skating' },
  { id: 'film', label: 'Film' },
  { id: 'finance', label: 'Finance' },
  { id: 'first-amendment', label: 'First Amendment' },
  { id: 'firsts', label: 'Firsts' },
  { id: 'football', label: 'Football' },
  { id: 'founding-era', label: 'Founding Era' },
  { id: 'frontier', label: 'Frontier' },
  { id: 'free-people-of-color', label: 'Free People of Color' },
  { id: 'freedom', label: 'Freedom' },
  { id: 'fugitive-slave-law', label: 'Fugitive Slave Law' },
  { id: 'genealogy', label: 'Genealogy' },
  { id: 'gerrymandering', label: 'Gerrymandering' },
  { id: 'golf', label: 'Golf' },
  { id: 'government', label: 'Government' },
  { id: 'governors', label: 'Governors' },
  { id: 'grassroots-leadership', label: 'Grassroots Leadership' },
  { id: 'great-migration', label: 'Great Migration' },
  { id: 'greenwood', label: 'Greenwood' },
  { id: 'gymnastics', label: 'Gymnastics' },
  { id: 'hall-of-fame', label: 'Hall of Fame' },
  { id: 'healthcare', label: 'Healthcare' },
  { id: 'harlem', label: 'Harlem' },
  { id: 'harlem-renaissance', label: 'Harlem Renaissance' },
  { id: 'hbcu', label: 'HBCUs' },
  { id: 'higher-education', label: 'Higher Education' },
  { id: 'history', label: 'History' },
  { id: 'hockey', label: 'Hockey' },
  { id: 'house-of-representatives', label: 'House of Representatives' },
  { id: 'housing', label: 'Housing' },
  { id: 'interstate-travel', label: 'Interstate Travel' },
  { id: 'invention', label: 'Invention' },
  { id: 'jazz', label: 'Jazz' },
  { id: 'jim-crow', label: 'Jim Crow' },
  { id: 'journalism', label: 'Journalism' },
  { id: 'judiciary', label: 'Judiciary' },
  { id: 'jury-selection', label: 'Jury Selection' },
  { id: 'labor', label: 'Labor' },
  { id: 'land-ownership', label: 'Land Ownership' },
  { id: 'land-grant', label: 'Land Grant' },
  { id: 'law', label: 'Law' },
  { id: 'law-enforcement', label: 'Law Enforcement' },
  { id: 'leadership', label: 'Leadership' },
  { id: 'liberal-arts', label: 'Liberal Arts' },
  { id: 'library', label: 'Library' },
  { id: 'literature', label: 'Literature' },
  { id: 'marine-corps', label: 'Marine Corps' },
  { id: 'marriage', label: 'Marriage' },
  { id: 'maritime', label: 'Maritime' },
  { id: 'mass-mobilization', label: 'Mass Mobilization' },
  { id: 'mathematics', label: 'Mathematics' },
  { id: 'mayors', label: 'Mayors' },
  { id: 'media', label: 'Media' },
  { id: 'medicine', label: 'Medicine' },
  { id: 'memorial', label: 'Memorial' },
  { id: 'memory', label: 'Memory' },
  { id: 'migration', label: 'Migration' },
  { id: 'military', label: 'Military' },
  { id: 'movement', label: 'Movement' },
  { id: 'movement-churches', label: 'Movement Churches' },
  { id: 'museum', label: 'Museum' },
  { id: 'music', label: 'Music' },
  { id: 'nation-of-islam', label: 'Nation of Islam' },
  { id: 'national-capital', label: 'National Capital' },
  { id: 'national-mall', label: 'National Mall' },
  { id: 'navy', label: 'Navy' },
  { id: 'nonviolence', label: 'Nonviolence' },
  { id: 'northern-movement', label: 'Northern Movement' },
  { id: 'olympics', label: 'Olympics' },
  { id: 'opera', label: 'Opera' },
  { id: 'organizing', label: 'Organizing' },
  { id: 'organizing-schools', label: 'Organizing Schools' },
  { id: 'pan-africanism', label: 'Pan Africanism' },
  { id: 'peonage', label: 'Peonage' },
  { id: 'philanthropy', label: 'Philanthropy' },
  { id: 'philosophy', label: 'Philosophy' },
  { id: 'photography', label: 'Photography' },
  { id: 'physics', label: 'Physics' },
  { id: 'police-violence', label: 'Police Violence' },
  { id: 'politics', label: 'Politics' },
  { id: 'poverty', label: 'Poverty' },
  { id: 'preservation', label: 'Preservation' },
  { id: 'press', label: 'Press' },
  { id: 'president', label: 'President' },
  { id: 'property-ownership', label: 'Property Ownership' },
  { id: 'public-accommodations', label: 'Public Accommodations' },
  { id: 'public-safety', label: 'Public Safety' },
  { id: 'public-transit', label: 'Public Transit' },
  { id: 'publication', label: 'Publication' },
  { id: 'publishing', label: 'Publishing' },
  { id: 'railroad', label: 'Railroad' },
  { id: 'rebellion', label: 'Rebellion' },
  { id: 'reconstruction', label: 'Reconstruction' },
  { id: 'redlining', label: 'Redlining' },
  { id: 'religion', label: 'Religion' },
  { id: 'research', label: 'Research' },
  { id: 'resilience', label: 'Resilience' },
  { id: 'resistance', label: 'Resistance' },
  { id: 'restrictive-covenants', label: 'Restrictive Covenants' },
  { id: 'right-to-counsel', label: 'Right to Counsel' },
  { id: 'school-desegregation', label: 'School Desegregation' },
  { id: 'science', label: 'Science' },
  { id: 'sectionalism', label: 'Sectionalism' },
  { id: 'segregation', label: 'Segregation' },
  { id: 'self-defense', label: 'Self Defense' },
  { id: 'self-determination', label: 'Self Determination' },
  { id: 'self-governance', label: 'Self Governance' },
  { id: 'senate', label: 'Senate' },
  { id: 'settlement', label: 'Settlement' },
  { id: 'sit-ins', label: 'Sit-Ins' },
  { id: 'space', label: 'Space' },
  { id: 'sports', label: 'Sports' },
  { id: 'student-activism', label: 'Student Activism' },
  { id: 'student-movement', label: 'Student Movement' },
  { id: 'sundown-towns', label: 'Sundown Towns' },
  { id: 'supreme-court', label: 'Supreme Court' },
  { id: 'sweet-auburn', label: 'Sweet Auburn' },
  { id: 'teaching', label: 'Teaching' },
  { id: 'technology', label: 'Technology' },
  { id: 'television', label: 'Television' },
  { id: 'tennis', label: 'Tennis' },
  { id: 'theater', label: 'Theater' },
  { id: 'town', label: 'Town' },
  { id: 'track-and-field', label: 'Track and Field' },
  { id: 'transportation', label: 'Transportation' },
  { id: 'treme', label: 'Treme' },
  { id: 'underground-railroad', label: 'Underground Railroad' },
  { id: 'unions', label: 'Unions' },
  { id: 'vice-president', label: 'Vice President' },
  { id: 'voting-rights', label: 'Voting Rights' },
  { id: 'women', label: 'Women' },
  { id: 'women-leaders', label: 'Women Leaders' },
  { id: 'womens-education', label: "Women's Education" },
  { id: 'workers-rights', label: 'Workers Rights' },
  { id: 'youth-organizing', label: 'Youth Organizing' },
];

export const TOPIC_REGISTRY: readonly TopicDefinition[] = RAW_TOPIC_ENTRIES.map((entry) => ({
  ...entry,
  schemaVersion: TOPIC_TAXONOMY_SCHEMA_VERSION,
}));

export const TOPIC_REGISTRY_BY_ID: ReadonlyMap<string, TopicDefinition> = new Map(
  TOPIC_REGISTRY.map((topic) => [topic.id, topic]),
);

const TOPIC_IDS = new Set(TOPIC_REGISTRY.map((topic) => topic.id));

/** True when `id` is a member of the controlled topic taxonomy above. */
export function isValidTopicId(id: string): boolean {
  return TOPIC_IDS.has(id);
}

/** Display label for a topic id, or undefined when the id isn't in the registry. */
export function getTopicLabel(id: string): string | undefined {
  return TOPIC_REGISTRY_BY_ID.get(id)?.label;
}
