
/**
 * Firebase client and Admin helpers shared across BlackStory surfaces.
 * Production project:. Local defaults: demo-repo emulators.
 */
export {
  ADMIN_APP_ID,
  DEMO_PROJECT_ID,
  FIREBASE_PACKAGE,
  PRODUCTION_API_KEY,
  PRODUCTION_AUTH_DOMAIN,
  PRODUCTION_BREAK_GLASS_ENV,
  PRODUCTION_HOSTING_SITE,
  PRODUCTION_MESSAGING_SENDER_ID,
  PRODUCTION_PROJECT_ID,
  PRODUCTION_PROJECT_NUMBER,
  PRODUCTION_STORAGE_BUCKET,
  REGISTERED_APPS,
  WEB_APP_ID,
} from './constants.js';
export type { FirebaseSurface, RegisteredWebApp } from './constants.js';

export {
  assertFirebaseProjectAllowed,
  hasEmulatorSignals,
  isEmulatorHost,
  resolveFirebaseRuntimeMode,
} from './guard.js';
export type { EnvironmentLike, FirebaseRuntimeMode } from './guard.js';

export {
  firebaseClientConfigSchema,
  parseAdminFirebaseEnv,
  parseServerFirebaseEnv,
  parseWebFirebaseEnv,
} from './env.js';
export type {
  FirebaseClientConfig,
  ParsedFirebaseClientEnv,
  ParsedFirebaseServerEnv,
} from './env.js';

export {
  applyAdminEmulatorEnvironment,
  connectClientEmulators,
  getAdminEmulatorServices,
  readEmulatorHosts,
} from './emulators.js';
export type { EmulatorHosts } from './emulators.js';

export {
  configureAppCheckDebugToken,
  getAppCheckRequestHeaders,
  initializeAppCheckScaffold,
} from './app-check.js';
export type { AppCheckClientRuntime, AppCheckScaffoldOptions } from './app-check.js';
export {
  APP_CHECK_HEADER,
  createAppCheckGuard,
  createFirebaseAppCheckVerifier,
  parseAppCheckMode,
  readAppCheckToken,
} from './app-check-enforce.js';
export type {
  AppCheckDecision,
  AppCheckFailureReason,
  AppCheckGuardOptions,
  AppCheckHeaders,
  AppCheckMode,
  AppCheckRequest,
  AppCheckTelemetry,
  AppCheckTelemetryEvent,
  AppCheckVerifier,
  TrustedServiceIdentity,
  VerifiedAppCheckToken,
} from './app-check-enforce.js';

export { createWebFirebaseClient } from './web-client.js';
export type { WebFirebaseClient } from './web-client.js';

export { createAdminFirebaseClient } from './admin-client.js';
export type { AdminFirebaseClient } from './admin-client.js';
export * from './admin-auth.js';

export {
  createServerFirebaseApp,
  ensureGoogleCloudQuotaProject,
  getServerFirebaseApp,
  getServerFirestore,
} from './server.js';
export type { ServerFirebaseApp } from './server.js';

export {
  FIRESTORE_ROOT,
  firestorePaths,
  authClaimFlagsSchema,
  entityKindSchema,
  geoPointFieldsSchema,
  geoGeometrySchema,
  zipCodeInputSchema,
  geographicMatchSchema,
  entityLocationSchema,
  entityRelationshipSchema,
  entityMergeSchema,
  policyActiveSchema,
  policyVersionSchema,
  canonicalEntitySchema,
  claimTemporalContextSchema,
  claimGeographicContextSchema,
  confidenceComponentsSchema,
  confidenceScoreSchema,
  preservedClaimValueSchema,
  claimVersionSchema,
  researchCoverageSchema,
  relevanceMeasurementSchema,
  connectionStrengthSchema,
  canonicalClaimSchema,
  claimEvidenceLinkSchema,
  volatilityClassSchema,
  reviewIntervalSchema,
  verificationPolicySchema,
  verificationStatusSchema,
  verificationSubjectTypeSchema,
  verificationStateSchema,
  candidateUpdateStatusSchema,
  candidateUpdateSchema,
  contentHashSchema,
  rightsStatusSchema,
  publicationPermissionSchema,
  prohibitedUseSchema,
  rightsPolicySchema,
  sourceOrganizationSchema,
  sourceDomainSchema,
  evidenceSourceSchema,
  sourceItemSchema,
  retrievalEventSchema,
  sourceCaptureSchema,
  evidenceLocatorSchema,
  evidenceRecordSchema,
  evidenceLineageSchema,
  publicationReleaseSchema,
  publicActiveReleaseSchema,
  publicEntityProjectionSchema,
  publicSearchIndexSchema,
  submissionInboxSchema,
  auditActorSchema,
  auditSubjectSchema,
  auditEventSchema,
  outboxMessageSchema,
  idempotencyRecordSchema,
  outboxConsumerReceiptSchema,
  killSwitchSchema,
  discoveryCampaignRunSchema,
  parseWithSchema,
  policyActiveConverter,
  policyVersionConverter,
  canonicalEntityConverter,
  entityLocationConverter,
  entityRelationshipConverter,
  entityMergeConverter,
  canonicalClaimConverter,
  claimVersionConverter,
  claimEvidenceLinkConverter,
  sourceOrganizationConverter,
  sourceDomainConverter,
  evidenceSourceConverter,
  sourceItemConverter,
  sourceCaptureConverter,
  retrievalEventConverter,
  evidenceRecordConverter,
  evidenceLineageConverter,
  publicationReleaseConverter,
  publicActiveReleaseConverter,
  publicEntityProjectionConverter,
  preparePublicEntityProjectionForWrite,
  DEFAULT_PUBLIC_MEDIA_BUCKET,
  entityPrimaryImageObjectPath,
  entityPrimaryImageObjectRef,
  buildReleaseCatalogArtifacts,
  publicMediaObjectUrl,
  publicReleaseEntitiesListPath,
  publicReleaseSearchIndexPath,
  writeReleaseCatalogArtifactsToDir,
  uploadReleaseCatalogArtifacts,
  submissionInboxConverter,
  auditEventConverter,
  outboxMessageConverter,
  idempotencyRecordConverter,
  outboxConsumerReceiptConverter,
  killSwitchConverter,
  discoveryCampaignRunConverter,
  createAdminAtomicStore,
  commitWithAudit,
  consumeOutboxMessage,
  loadEntityPublicationHistory,
  resolveStaffRoles,
  canPublish,
  canResearchWrite,
  researchMayPublish,
  RELEASE_ACTIVATION_STATUSES,
  parseImmutablePublicationRelease,
  resolveActivePublicRelease,
  activatePublicationRelease,
  promoteClaimToPublicationCandidate,
  RESEARCH_CASE_SERVER_ACTIONS,
  assertResearchCaseActionAuthorized,
  assertResearchCaseTransitionAuthorized,
  executeAuthorizedResearchCaseTransition,
  executeAuthorizedResearchCaseAction,
} from './firestore/index.js';
export {
  DISCOVERY_CAMPAIGN_RUN_STATUSES,
  DISCOVERY_CAMPAIGN_RUN_MODES,
  RESEARCH_CAMPAIGNS_KILL_SWITCH_ID,
  buildDiscoveryCampaignRunDoc,
  assertDiscoveryRunCannotPublish,
  createInMemoryDiscoveryCampaignRunStore,
  isKillSwitchEngagedFromDoc,
  isResearchCampaignsKillSwitchEngaged,
  fetchResearchCampaignsKillSwitch,
  isResearchCampaignsKillSwitchEngagedIn,
  DISCOVERY_CATALOG_PROFILE_DEFAULT_MAX,
  resolutionProfileFromCatalogLeaf,
  resolutionProfileFromPublicSearchIndex,
  publicSearchIndexDocFromRow,
  loadDiscoveryCatalogProfiles,
  createPublicSearchIndexCatalogPager,
  createFirestorePublicSearchIndexCatalogPager,
} from './discovery/index.js';
export type {
  DiscoveryCampaignRunStatus,
  DiscoveryCampaignRunMode,
  BuildDiscoveryCampaignRunInput,
  DiscoveryCampaignRunStore,
  KillSwitchDocSnapshot,
  DocGetter,
  DiscoveryCatalogLeaf,
  DiscoveryCatalogPage,
  DiscoveryCatalogPager,
} from './discovery/index.js';
export {
  EMBEDDING_MODEL,
  EMBEDDING_DIMS,
  FIRESTORE_VECTOR_DIM_CAP,
  PLATFORM_MAX_NEIGHBORS,
  ENTITY_EMBEDDINGS_COLLECTION,
  VECTOR_FIELD_NAME,
  DISTANCE_MEASURE,
  VECTOR_INDEX_READ_METERING_DIVISOR,
  STANDARD_INDEX_READ_METERING_DIVISOR,
  APPROX_USD_PER_1K_TOKENS,
  APPROX_TOKENS_PER_CHAR,
  InvalidEmbeddingVectorError,
  magnitude,
  normalizeVector,
  truncateVector,
  truncateAndNormalize,
  dotProduct,
  dotProductDistance,
  isUnitVector,
  assertValidEmbeddingVector,
  resolveEntityYearSpan,
  deriveEraBucket,
  deriveEntityFilters,
  buildEntityEmbeddingText,
  EmbeddingProviderError,
  createRetryingEmbeddingProvider,
  createDeterministicMockEmbeddingProvider,
  createGeminiEmbeddingProvider,
  embedEntity,
  embedEntitiesBatch,
  estimateEmbeddingCostUsd,
  sha256Hex,
  createAdminVectorIndexStore,
  createInMemoryVectorIndexStore,
  runBackfill,
  createFirestoreCanonicalEntitySource,
  createFirestoreExistingHashLookup,
  createFirestorePublicSearchIndexEntitySource,
  createNationalCatalogFixtureEntitySource,
  mapSearchIndexRecordToEmbeddingInput,
  mapCatalogFixtureRecordToEmbeddingInput,
  parseStateCodeFromJurisdiction,
} from './embeddings/index.js';
export type {
  EmbeddingVector,
  EntityLocationContext,
  EntityEmbeddingSource,
  EntityVectorFilters,
  EmbeddingProvider,
  RetryOptions,
  MockEmbeddingProviderOptions,
  GeminiEmbeddingProviderOptions,
  GeminiEmbedContentClient,
  EntityEmbeddingInput,
  EntityEmbeddingResult,
  EmbedEntityOptions,
  BatchEmbedOptions,
  BatchEmbedResult,
  EntityEmbeddingDoc,
  VectorQueryInput,
  VectorQueryMatch,
  VectorIndexStore,
  BackfillOptions,
  BackfillSummary,
  BackfillEntitySourceName,
  CanonicalEntitySource,
  CanonicalEntitySourcePage,
  ExistingEmbeddingHashLookup,
  SearchIndexEmbeddingRecord,
  CatalogFixtureEmbeddingRecord,
} from './embeddings/index.js';
export type {
  FirestoreRootCollection,
  AuthClaimFlags,
  EntityKindDoc,
  GeoPointFields,
  GeoGeometryDoc,
  ZipCodeInputDoc,
  GeographicMatchDoc,
  EntityLocationDoc,
  EntityRelationshipDoc,
  EntityMergeDoc,
  ConfidenceComponentsDoc,
  ConfidenceScoreDoc,
  PreservedClaimValueDoc,
  ClaimVersionDoc,
  CanonicalClaimDoc,
  ClaimEvidenceLinkDoc,
  VolatilityClassDoc,
  ReviewIntervalDoc,
  VerificationPolicyDoc,
  VerificationStatusDoc,
  VerificationSubjectTypeDoc,
  VerificationStateDoc,
  CandidateUpdateStatusDoc,
  CandidateUpdateDoc,
  PolicyActiveDoc,
  PolicyVersionDoc,
  CanonicalEntityDoc,
  ContentHashDoc,
  RightsPolicyDoc,
  SourceOrganizationDoc,
  SourceDomainDoc,
  EvidenceSourceDoc,
  SourceItemDoc,
  RetrievalEventDoc,
  SourceCaptureDoc,
  EvidenceLocatorDoc,
  EvidenceRecordDoc,
  EvidenceLineageDoc,
  PublicationReleaseDoc,
  PublicActiveReleaseDoc,
  PublicEntityProjectionDoc,
  PublicSearchIndexDoc,
  SubmissionInboxDoc,
  AuditEventDoc,
  OutboxMessageDoc,
  IdempotencyRecordDoc,
  OutboxConsumerReceiptDoc,
  KillSwitchDoc,
  DiscoveryCampaignRunDoc,
  AtomicSnapshot,
  AtomicTransaction,
  AtomicStore,
  StateMutation,
  CommitWithAuditInput,
  CommitWithAuditResult,
  ConsumeOutboxResult,
  StaffRole,
  ReleaseActivationStatus,
  ImmutablePublicationReleaseDoc,
  ActivePublicReleasePointer,
  ActivateReleaseInput,
  ActivateReleaseResult,
  AcceptedPromotionDoc,
  PublicationCandidateDoc,
  PromoteClaimInput,
  PromoteClaimResult,
  ResearchCaseServerAction,
  ServerResearchCaseState,
  BuiltReleaseCatalogArtifacts,
  ReleaseEntitiesListArtifact,
  ReleaseSearchIndexArtifact,
} from './firestore/index.js';

// Census/ACS/FBI-UCR national-rollup readers for the public /data page (the related workstream,
// the related workstream). Admin-SDK aggregate reads only — never a per-record dump. holcAreas is
// deliberately absent here; its CC BY-NC-SA rights gate excludes it from every public reader.
export {
  getNationalPopulationByDecade,
  getNationalPopulationChanges,
  getStatePopulationByDecade,
  getStatePopulationChanges,
  getAcsCoverageSummary,
  getHateCrimeYearSummary,
  getHateCrimeYearSummaries,
  hateCrimeAntiBlackShare,
  getOpportunityAtlasCoverageSummary,
  aggregateOpportunityAtlasCoverage,
  buildStateFipsNameMap,
  resolveStateFipsName,
  publicSourceUrl,
  POPULATION_DECADE_COMPARABILITY_NOTE,
  US_TERRITORY_FIPS_NAMES,
  OPPORTUNITY_ATLAS_OUTCOME_FIELD_LABELS,
  KFR_BLACK_P25_HISTOGRAM_BINS,
  aggregateCountiesByState,
  computePopulationDecadeChange,
  computeStatePopulationChange,
  computeNationalPopulationChangesFromDecades,
  computeStatePopulationChangesFromDecades,
} from './demographics/national-stats.js';
export type {
  NationalPopulationByDecade,
  PopulationDecadeChange,
  StatePopulationByDecade,
  StatePopulationChange,
  AcsCoverageSummary,
  HateCrimeYearSummary,
  OpportunityAtlasCoverageSummary,
  OpportunityAtlasOutcomeFieldCoverage,
  OpportunityAtlasHistogramBin,
} from './demographics/national-stats.js';
export {
  censusCountyDecadeSchema,
  censusCountyDecadeDecadeSchema,
  censusCountyDecadeId,
  parseCensusCountyDecadeDoc,
  acsCountyProfileSchema,
  acsTractProfileSchema,
} from './demographics/schema.js';
export type {
  CensusCountyDecadeDoc,
  CensusCountyDecadeDecade,
  AcsCountyProfileDoc,
  AcsTractProfileDoc,
} from './demographics/schema.js';
