/**
 * Firebase client and Admin helpers shared across Black Book surfaces.
 * Production project: black-book-efaaf. Local defaults: demo-black-book emulators.
 */
export {
  ADMIN_APP_ID,
  DEMO_PROJECT_ID,
  FIREBASE_PACKAGE,
  PRODUCTION_API_KEY,
  PRODUCTION_AUTH_DOMAIN,
  PRODUCTION_BREAK_GLASS_ENV,
  PRODUCTION_HOSTING_SITE,
  PRODUCTION_MESSAGING_SENDER_ID,
  PRODUCTION_PROJECT_ID,
  PRODUCTION_PROJECT_NUMBER,
  PRODUCTION_STORAGE_BUCKET,
  REGISTERED_APPS,
  WEB_APP_ID,
} from './constants.js';
export type { FirebaseSurface, RegisteredWebApp } from './constants.js';

export {
  assertFirebaseProjectAllowed,
  hasEmulatorSignals,
  isEmulatorHost,
  resolveFirebaseRuntimeMode,
} from './guard.js';
export type { EnvironmentLike, FirebaseRuntimeMode } from './guard.js';

export {
  firebaseClientConfigSchema,
  parseAdminFirebaseEnv,
  parseServerFirebaseEnv,
  parseWebFirebaseEnv,
} from './env.js';
export type {
  FirebaseClientConfig,
  ParsedFirebaseClientEnv,
  ParsedFirebaseServerEnv,
} from './env.js';

export {
  applyAdminEmulatorEnvironment,
  connectClientEmulators,
  getAdminEmulatorServices,
  readEmulatorHosts,
} from './emulators.js';
export type { EmulatorHosts } from './emulators.js';

export {
  configureAppCheckDebugToken,
  getAppCheckRequestHeaders,
  initializeAppCheckScaffold,
} from './app-check.js';
export type { AppCheckClientRuntime, AppCheckScaffoldOptions } from './app-check.js';
export {
  APP_CHECK_HEADER,
  createAppCheckGuard,
  createFirebaseAppCheckVerifier,
  parseAppCheckMode,
  readAppCheckToken,
} from './app-check-enforce.js';
export type {
  AppCheckDecision,
  AppCheckFailureReason,
  AppCheckGuardOptions,
  AppCheckHeaders,
  AppCheckMode,
  AppCheckRequest,
  AppCheckTelemetry,
  AppCheckTelemetryEvent,
  AppCheckVerifier,
  TrustedServiceIdentity,
  VerifiedAppCheckToken,
} from './app-check-enforce.js';

export { createWebFirebaseClient } from './web-client.js';
export type { WebFirebaseClient } from './web-client.js';

export { createAdminFirebaseClient } from './admin-client.js';
export type { AdminFirebaseClient } from './admin-client.js';
export * from './admin-auth.js';

export { createServerFirebaseApp, getServerFirebaseApp, getServerFirestore } from './server.js';
export type { ServerFirebaseApp } from './server.js';

export {
  FIRESTORE_ROOT,
  firestorePaths,
  authClaimFlagsSchema,
  entityKindSchema,
  geoPointFieldsSchema,
  geoGeometrySchema,
  zipCodeInputSchema,
  geographicMatchSchema,
  entityLocationSchema,
  entityRelationshipSchema,
  entityMergeSchema,
  policyActiveSchema,
  policyVersionSchema,
  canonicalEntitySchema,
  claimTemporalContextSchema,
  claimGeographicContextSchema,
  confidenceComponentsSchema,
  confidenceScoreSchema,
  preservedClaimValueSchema,
  claimVersionSchema,
  researchCoverageSchema,
  relevanceMeasurementSchema,
  connectionStrengthSchema,
  canonicalClaimSchema,
  claimEvidenceLinkSchema,
  contentHashSchema,
  rightsStatusSchema,
  publicationPermissionSchema,
  prohibitedUseSchema,
  rightsPolicySchema,
  sourceOrganizationSchema,
  sourceDomainSchema,
  evidenceSourceSchema,
  sourceItemSchema,
  retrievalEventSchema,
  sourceCaptureSchema,
  evidenceLocatorSchema,
  evidenceRecordSchema,
  evidenceLineageSchema,
  publicationReleaseSchema,
  publicActiveReleaseSchema,
  publicEntityProjectionSchema,
  submissionInboxSchema,
  auditActorSchema,
  auditSubjectSchema,
  auditEventSchema,
  outboxMessageSchema,
  idempotencyRecordSchema,
  outboxConsumerReceiptSchema,
  killSwitchSchema,
  parseWithSchema,
  policyActiveConverter,
  policyVersionConverter,
  canonicalEntityConverter,
  entityLocationConverter,
  entityRelationshipConverter,
  entityMergeConverter,
  canonicalClaimConverter,
  claimEvidenceLinkConverter,
  sourceOrganizationConverter,
  sourceDomainConverter,
  evidenceSourceConverter,
  sourceItemConverter,
  sourceCaptureConverter,
  retrievalEventConverter,
  evidenceRecordConverter,
  evidenceLineageConverter,
  publicationReleaseConverter,
  publicActiveReleaseConverter,
  publicEntityProjectionConverter,
  submissionInboxConverter,
  auditEventConverter,
  outboxMessageConverter,
  idempotencyRecordConverter,
  outboxConsumerReceiptConverter,
  killSwitchConverter,
  createAdminAtomicStore,
  commitWithAudit,
  consumeOutboxMessage,
  loadEntityPublicationHistory,
  resolveStaffRoles,
  canPublish,
  canResearchWrite,
  researchMayPublish,
  RELEASE_ACTIVATION_STATUSES,
  parseImmutablePublicationRelease,
  resolveActivePublicRelease,
  activatePublicationRelease,
  promoteClaimToPublicationCandidate,
  RESEARCH_CASE_SERVER_ACTIONS,
  assertResearchCaseActionAuthorized,
  assertResearchCaseTransitionAuthorized,
  executeAuthorizedResearchCaseTransition,
  executeAuthorizedResearchCaseAction,
} from './firestore/index.js';
export {
  EMBEDDING_MODEL,
  EMBEDDING_DIMS,
  FIRESTORE_VECTOR_DIM_CAP,
  PLATFORM_MAX_NEIGHBORS,
  ENTITY_EMBEDDINGS_COLLECTION,
  VECTOR_FIELD_NAME,
  DISTANCE_MEASURE,
  VECTOR_INDEX_READ_METERING_DIVISOR,
  STANDARD_INDEX_READ_METERING_DIVISOR,
  APPROX_USD_PER_1K_TOKENS,
  APPROX_TOKENS_PER_CHAR,
  InvalidEmbeddingVectorError,
  magnitude,
  normalizeVector,
  truncateVector,
  truncateAndNormalize,
  dotProduct,
  dotProductDistance,
  isUnitVector,
  assertValidEmbeddingVector,
  resolveEntityYearSpan,
  deriveEraBucket,
  deriveEntityFilters,
  buildEntityEmbeddingText,
  EmbeddingProviderError,
  createRetryingEmbeddingProvider,
  createDeterministicMockEmbeddingProvider,
  createGeminiEmbeddingProvider,
  embedEntity,
  embedEntitiesBatch,
  estimateEmbeddingCostUsd,
  sha256Hex,
  createAdminVectorIndexStore,
  createInMemoryVectorIndexStore,
  runBackfill,
  createFirestoreCanonicalEntitySource,
  createFirestoreExistingHashLookup,
} from './embeddings/index.js';
export type {
  EmbeddingVector,
  EntityLocationContext,
  EntityEmbeddingSource,
  EntityVectorFilters,
  EmbeddingProvider,
  RetryOptions,
  MockEmbeddingProviderOptions,
  GeminiEmbeddingProviderOptions,
  GeminiEmbedContentClient,
  EntityEmbeddingInput,
  EntityEmbeddingResult,
  EmbedEntityOptions,
  BatchEmbedOptions,
  BatchEmbedResult,
  EntityEmbeddingDoc,
  VectorQueryInput,
  VectorQueryMatch,
  VectorIndexStore,
  BackfillOptions,
  BackfillSummary,
  CanonicalEntitySource,
  CanonicalEntitySourcePage,
  ExistingEmbeddingHashLookup,
} from './embeddings/index.js';
export type {
  FirestoreRootCollection,
  AuthClaimFlags,
  EntityKindDoc,
  GeoPointFields,
  GeoGeometryDoc,
  ZipCodeInputDoc,
  GeographicMatchDoc,
  EntityLocationDoc,
  EntityRelationshipDoc,
  EntityMergeDoc,
  ConfidenceComponentsDoc,
  ConfidenceScoreDoc,
  PreservedClaimValueDoc,
  ClaimVersionDoc,
  CanonicalClaimDoc,
  ClaimEvidenceLinkDoc,
  PolicyActiveDoc,
  PolicyVersionDoc,
  CanonicalEntityDoc,
  ContentHashDoc,
  RightsPolicyDoc,
  SourceOrganizationDoc,
  SourceDomainDoc,
  EvidenceSourceDoc,
  SourceItemDoc,
  RetrievalEventDoc,
  SourceCaptureDoc,
  EvidenceLocatorDoc,
  EvidenceRecordDoc,
  EvidenceLineageDoc,
  PublicationReleaseDoc,
  PublicActiveReleaseDoc,
  PublicEntityProjectionDoc,
  SubmissionInboxDoc,
  AuditEventDoc,
  OutboxMessageDoc,
  IdempotencyRecordDoc,
  OutboxConsumerReceiptDoc,
  KillSwitchDoc,
  AtomicSnapshot,
  AtomicTransaction,
  AtomicStore,
  StateMutation,
  CommitWithAuditInput,
  CommitWithAuditResult,
  ConsumeOutboxResult,
  StaffRole,
  ReleaseActivationStatus,
  ImmutablePublicationReleaseDoc,
  ActivePublicReleasePointer,
  ActivateReleaseInput,
  ActivateReleaseResult,
  AcceptedPromotionDoc,
  PublicationCandidateDoc,
  PromoteClaimInput,
  PromoteClaimResult,
  ResearchCaseServerAction,
  ServerResearchCaseState,
} from './firestore/index.js';
